
# ============================================================
# I BOB
# ============================================================
def add_bob1(doc):
    CH(doc,"I BOB. TALABALAR O'ZLASHTIRISHINI TAHLIL QILISHNING NAZARIY ASOSLARI")

    SH(doc,"1.1. Ta'lim sohasida axborot tizimlari va o'quv jarayonini raqamlashtirish")
    pp(doc,"Ta'lim sohasida axborot texnologiyalaridan foydalanish oxirgi o'n yillikda jadal rivojlanib bormoqda. Dastlab oddiy elektron jurnallar va hisobot tizimlari sifatida joriy etilgan ta'lim axborot tizimlari (TAS) bugun yaxlit boshqaruv platformalariga aylangan. Ular talabalar ro'yxati, dars jadvali, baholash, davomat, moliyaviy hisob-kitob va hisobot kabi barcha jarayonlarni birlashtirib, markazlashgan holda boshqaradi. UNESCO va OECD xalqaro tashkilotlarining tadqiqotlariga ko'ra, ta'limni raqamlashtirish samarali ta'lim natijalariga erishishda 25-40 foizgacha ijobiy ta'sir ko'rsatishi mumkin [7]. Ushbu ta'sir asosan ma'lumotlarga asoslangan qaror qabul qilish imkonini berishi, o'qituvchi va talabalar o'rtasidagi kommunikatsiyani yaxshilashi, hamda ta'lim jarayonini individuallashtirishga imkon berishi bilan bog'liq.")
    pp(doc,"Zamonaviy ta'lim axborot tizimlarini bir necha avlodga bo'lish mumkin. Birinchi avlod tizimlari (1990-2000-yillar) asosan ma'lumotlarni saqlash va oddiy hisobot funksiyalarini bajargan. Ushbu davrdagi tizimlar ko'pincha lokal serverda ishlagan, ma'lumotlar bazasi sifatida dBase, FoxPro yoki erta Microsoft SQL Server versiyalari qo'llanilgan. Foydalanuvchi interfeysi sodda matn asosidagi bo'lib, grafik imkoniyatlar deyarli yo'q edi. Ikkinchi avlod tizimlari (2000-2010-yillar) internet asosidagi platformalar bo'lib, masofaviy kirishni ta'minlagan va birinchi bor web brauzer orqali ishlash imkonini bergan. PHP, ASP va Java platformalari keng qo'llanilgan. Uchinchi avlod tizimlari (2010-hozirgacha) aqlli tahlil, mobil qurilmalar bilan integratsiya va real vaqt rejimidagi boshqaruvni o'z ichiga oladi. To'rtinchi avlod esa sun'iy intellekt va mashinali o'rganishni faol qo'llaydigan tizimlardan iborat bo'lib, predictive analytics, personalizatsiya va NLP (Natural Language Processing) kabi ilg'or texnologiyalarni tatbiq etadi [8].")
    pp(doc,"O'zbekistonda ta'limni raqamlashtirish sohasida muhim yutuqlarga erishilgan. O'zbekiston Respublikasi Prezidentining 2020-yil 5-oktyabrdagi PF-6079-sonli farmoni bilan tasdiqlangan «Raqamli O'zbekiston — 2030» strategiyasida ta'limni raqamlashtirish ustuvor yo'nalish sifatida belgilangan [2]. Ushbu strategiya doirasida 2018-yilda joriy etilgan HEMIS (Higher Education Management Information System) tizimi oliy ta'lim muassasalarining faoliyatini yagona platforma orqali boshqarish imkonini berdi. HEMIS orqali talabalar ma'lumotlari, o'quv rejalari, dars jadvali, o'qituvchilar yuklamasi va moliyaviy ko'rsatkichlar yagona bazada saqlanmoqda. Ammo HEMIS ning asosiy maqsadi ma'muriy hisobot va nazorat bo'lib, ta'lim analitikasi va prediktiv funksiyalar jihatidan cheklangan imkoniyatlarga ega. Shu sababli HEMIS ga qo'shimcha, foydalanuvchi uchun qulay va analitik imkoniyatlar boyroq bo'lgan maxsus platformalar ishlab chiqilishiga kuchli ehtiyoj sezilmoqda [3].")
    pp(doc,"Learning Management System (LMS) platformalari — Moodle, Canvas, Blackboard, Edmodo — jahon miqyosida keng tarqalgan. Ular kurs materiallari, vazifalar, testlar va baholar bilan ishlash imkonini beradi. Moodle dunyo bo'yicha 350 milliondan ortiq foydalanuvchiga ega va 100 dan ko'proq mamlakatda qo'llaniladi. Canvas esa AQSHdagi ko'plab universitetlarda asosiy LMS sifatida qabul qilingan. Biroq ushbu tizimlar, asosan, o'quv kontentini boshqarishga mo'ljallangan bo'lib, o'zlashtirish ko'rsatkichlari bo'yicha chuqur statistik tahlil, individual talaba bo'yicha bashorat qilish va real vaqt rejimida kuzatuv funksiyalari yetarlicha rivojlanmagan. Bu esa ta'lim analitikasiga maxsus e'tibor qaratuvchi alohida tizim yaratish zaruriyatini ko'rsatib turibdi [9].")
    pp(doc,"Raqamlashtirish jarayonida ma'lumotlar xavfsizligi va maxfiylikni ta'minlash alohida ahamiyat kasb etadi. Yevropa Ittifoqining GDPR (General Data Protection Regulation — Umumiy Ma'lumotlarni Himoya qilish Qoidalari) va O'zbekiston Respublikasining «Shaxsga doir ma'lumotlar to'g'risida»gi qonuniga muvofiq, talabalar shaxsiy ma'lumotlari qat'iy himoyalanishi shart [10]. Zamonaviy ta'lim platformalari SSL/TLS shifrlash, RBAC (rol asosidagi kirish nazorati) va audit log mexanizmlaridan foydalanishi lozim. Bundan tashqari, ma'lumotlar bazasini zaxiralash (backup), so'rovlarni jurnallashtirish (logging) va intrusionni aniqlash tizimlari (IDS) ham platformaning xavfsizlik arxitekturasining ajralmas qismini tashkil etadi. Ushbu diplom loyihasida ishlab chiqilgan platforma ham ushbu barcha xavfsizlik talablariga to'liq rioya qiladi.")
    pp(doc,"API (Application Programming Interface) integratsiya zamonaviy ta'lim ekosistemalarining muhim xususiyatidir. Turli tizimlar o'rtasida ma'lumot almashish uchun RESTful API, GraphQL yoki WebSocket protokollari qo'llaniladi. Ushbu platforma RESTful API arxitekturasiga asoslanib, kelajakda HEMIS, bank tizimlari, kutubxona tizimlari va mobil ilovalar bilan integratsiya qilish imkoniyatini ta'minlaydi. OAuth 2.0 va OpenID Connect protokollari orqali single sign-on (SSO) ham amalga oshirilishi mumkin, bu esa foydalanuvchilar uchun yagona kirish nuqtasini ta'minlaydi.")
    tbl(doc,"Dunyoning yetakchi ta'lim axborot tizimlarining qiyosiy tavsifi",tn(1),
        ["Tizim","Turi","Asosiy funksiya","Analitika","ML imkoni","Narxi"],
        [["HEMIS","Davlat TAS","Ma'muriy boshqaruv","Cheklangan","Yo'q","Bepul"],
         ["Moodle","LMS","Kurs boshqaruvi","O'rtacha","Plaginlar","Bepul"],
         ["Canvas","LMS","Ta'lim kontenti","O'rtacha","Cheklangan","To'lovli"],
         ["Blackboard","LMS","Korporativ ta'lim","Yaxshi","Mavjud","To'lovli"],
         ["Google Classroom","LMS","Oddiy boshqaruv","Kam","Yo'q","Bepul"],
         ["Ushbu platforma","Web TAS","Tahlil+Boshqaruv","Kuchli","Mavjud","Ochiq manba"]],
        widths=[3,2.5,3.5,2.5,2.5,2])

    SH(doc,"1.2. Talabalar o'zlashtirishini baholash va ko'rsatkichlari")
    pp(doc,"Talabalar o'zlashtirishini baholash tizimi ta'lim jarayonining markaziy elementi hisoblanadi. O'zbekiston oliy ta'lim tizimida kredit-modul tizimi joriy etilgan bo'lib, har bir fan bo'yicha talaba joriy nazorat (JN), oraliq nazorat (ON) va yakuniy nazorat (YN) natijalariga asosan umumiy ball to'playdi [1]. Ushbu tizimda maksimal ball 100 ga teng: JN uchun 40, ON uchun 20 va YN uchun 40 ball ajratilgan. JN davomida talabalar mustaqil ishlar, laboratoriya ishlari, kollokviumlar va amaliy mashg'ulotlarda baholanadi. ON semestr o'rtasida o'tkaziladigan yozma imtihon bo'lib, nazariy va amaliy bilimlarni tekshiradi. YN esa semestr oxirida o'tkaziladigan asosiy imtihon hisoblanadi.")
    pp(doc,"GPA (Grade Point Average — O'rtacha Ball Ko'rsatkichi) talabaning umumiy akademik o'zlashtirishini ifodalovchi asosiy metrika hisoblanadi. 4.0 shkala bo'yicha hisoblangan GPA talabaning stipendiya, magistraturaga qabul qilinish va ishga kirishida muhim rol o'ynaydi. O'zbekiston oliy ta'lim tizimida qo'llaniladigan 100 ballik shkala bo'yicha: 86-100 ball a'lo (GPA 4.0), 71-85 ball yaxshi (GPA 3.0), 56-70 ball qoniqarli (GPA 2.0), 55 va undan past qoniqarsiz (GPA 0.0) deb hisoblanadi. Semestr GPA si o'sha semestrda o'tilgan barcha fanlarning kreditlar og'irligini hisobga olgan holda hisoblangan o'rtacha baho hisoblanadi. Kümülyatif GPA (CGPA) esa talabaning butun o'qish davri uchun hisoblangan umumiy o'rtacha baho ko'rsatkichidir.")
    pp(doc,"O'zlashtirish ko'rsatkichlarini tahlil qilishda bir qator muhim statistik metrikalar qo'llaniladi. O'rtacha baho (mean score) va mediana guruh bo'yicha markaziy tendensiyani ko'rsatadi. Standart og'ish (standard deviation) guruh ichidagi farqlanish darajasini ifodalaydi — yuqori standart og'ish guruh tarkibining heterogen ekanligini ko'rsatadi. Yuqori va pastki kvartillar (Q1 va Q3) va ularning farqi (IQR — Interquartile Range) ekstremal qiymatlarning ta'siridan himoyalangan tarqalish ko'rsatkichi sifatida ishlatiladi. Min-Max ko'rsatkichlari esa guruhning eng yaxshi va eng yomon natijalarini belgilaydi. Ushbu statistika platformada har bir fan va guruh uchun avtomatik hisoblanadi va dinamik ravishda yangilanadi [11].")
    pp(doc,"Akademik xavf (academic risk) — talabaning semestr davomida qoniqarsiz baho olishi yoki o'quv dasturidan chetlashtirilish ehtimoli. Akademik xavfni aniqlashda bir necha ko'rsatkichlar kombinatsiyasi qo'llaniladi: joriy JN ballari, davomat foizi, oldingi semestrlardagi ko'rsatkichlar, fan murakkabligi va individual xususiyatlar. Erta ogohlantirish tizimlari (Early Warning Systems, EWS) semestr boshidanoq xavf ostidagi talabalarni aniqlashga mo'ljallangan. Tadqiqotlar shuni ko'rsatadiki, semestrning birinchi 4-6 haftasidagi ma'lumotlar asosida 75-80 foiz aniqlik bilan yakuniy natijani bashorat qilish mumkin [4, 12].")
    pp(doc,"Akademik qarzdorlik (academic debt) semestr oxirida 55 baldan past natija ko'rsatgan talabalar uchun qo'shimcha imtihon olish imkoniyati. Qarzdorlik holatini kuzatish va ularni o'z vaqtida hal qilishga yordam berish nafaqat talaba, balki o'qituvchi va dekanat uchun ham muhimdir. O'zbekiston oliy ta'lim tizimida talabalar qarzdorlikni belgilangan muddat ichida (odatda keyingi semestr boshiga qadar) bartaraf etishlari shart. Aksi holda talaba o'qishdan chiqarib yuborilishi mumkin. Statistikaga ko'ra, o'z vaqtida aniqlangan akademik qarzdorliklarning 70 foizini qayta ishlash va qo'shimcha mashg'ulotlar orqali bartaraf etish mumkin. Shu sababli platforma avtomatik ravishda qarzdorlik yuzaga kelishi bilanoq o'qituvchi va talabani xabardor qilishi lozim.")
    pp(doc,"Davomat ko'rsatkichi (attendance rate) o'zlashtirish bilan kuchli korrelyatsion bog'liqlikka ega ekanligini ko'plab tadqiqotlar tasdiqlaydi. Turli universitetlardagi tadqiqotlar shuni ko'rsatadiki, darsga qatnashish foizi 80 foizdan past bo'lgan talabalar akademik muvaffaqiyatsizlik xavfiga 3 baravar ko'proq duch keladi [4]. Shu sababli ushbu platformada davomat va baho o'rtasidagi korrelyatsiyani vizualizatsiya qilish alohida grafik modul sifatida amalga oshirilgan. O'qituvchilar dars davomida davomat belgisini elektron tarzda kiritadi — Keldi (present), Kelmadi (absent) yoki Kech keldi (late) — va tizim avtomatik ravishda statistikani yangilab boradi. Yig'ilgan davomat ma'lumotlari ML modelining eng muhim kirishlaridan biri sifatida ham ishlatiladi.")
    tbl(doc,"Baholash tizimi va GPA hisobi",tn(1),
        ["Ball (100 tizim)","Baho","GPA (4.0 tizim)","Ta'rif","Miqdori (%)"],
        [["86 – 100","A'lo","4.0","Excellent","Taxminan 25%"],
         ["71 – 85","Yaxshi","3.0","Good","Taxminan 35%"],
         ["56 – 70","Qoniqarli","2.0","Satisfactory","Taxminan 28%"],
         ["0 – 55","Qoniqarsiz","0.0","Unsatisfactory","Taxminan 12%"]],
        widths=[3.5,3,3.5,3,2.5])

    SH(doc,"1.3. Ma'lumotlarni vizualizatsiya va grafik tahlil qilish usullari")
    pp(doc,"Ma'lumotlarni vizualizatsiya qilish — murakkab raqamli ma'lumotlarni insonlar uchun tushunarliroq grafik, diagramma va xarita shaklida ifodalash san'ati va fanidir. Vizualizatsiya nazariyasining asoschisi hisoblangan Edward Tufte o'zining mashhur «The Visual Display of Quantitative Information» asarida yaxshi vizualizatsiyaning asosiy prinsiplarini belgilab berdi: ma'lumotni vizual jihatdan kodlash samaradorligi, keraksiz «grafikdan murabba» (chartjunk) dan xalos bo'lish, va ma'lumotni maksimal zichlikda eng kam grafik elementlar bilan ifodalash [13]. Ta'lim analitikasida vizualizatsiya ayniqsa muhim, chunki o'qituvchilar va ma'murlar ko'pincha katta hajmdagi ma'lumotlarni tezda o'qib, qaror qabul qilishlari zarur. Yaxshi vizualizatsiya bu jarayonni sezilarli darajada tezlashtiradi va xato qarorlarning oldini oladi.")
    pp(doc,"Ta'lim ma'lumotlari uchun eng ko'p ishlatiladigan vizualizatsiya turlari quyidagilardan iborat. Birinchi tur — Chiziqli grafik (Line chart): vaqt o'qi (x) bo'ylab o'zlashtirish ko'rsatkichlarining dinamikasini ko'rsatish uchun ideal. Semestr boshidan oxirigacha JN, ON va yakuniy balllarning o'zgarishi, yillik GPA dinamikasi kabi ko'rsatkichlar uchun ishlatiladi. Ikkinchi tur — Ustunli diagramma (Bar/Column chart): turli fanlar yoki guruhlar bo'yicha qiyosiy tahlil uchun samarali. Grouped va Stacked variantlari turli tahlil maqsadlari uchun qo'llaniladi. Uchinchi tur — Doira va halqa diagrammasi (Pie/Donut chart): taqsimot nisbatlarini ko'rsatish uchun — a'lo, yaxshi, qoniqarli va qoniqarsiz baholalar nisbati kabi. To'rtinchi tur — Issiqlik xaritasi (Heatmap): matritsa ko'rinishida ko'p o'lchovli ma'lumotlar uchun. Beshinchi tur — Tarqalish diagrammasi (Scatter plot): ikkita o'zgaruvchi — masalan davomat va baho — o'rtasidagi korrelyatsiyani ko'rsatish uchun. Oltinchi tur — Radar diagrammasi (Spider chart): ko'p fan bo'yicha talaba profilini poligon ko'rinishida taqqoslash uchun [14].")
    pp(doc,"Frontend texnologiyalarda vizualizatsiya uchun D3.js, Chart.js, Recharts, Highcharts, Victory, Nivo kabi kutubxonalar keng qo'llaniladi. D3.js eng kuchli va moslashuvchan kutubxona hisoblanib, har qanday maxsus vizualizatsiyani yaratish imkonini beradi, ammo o'rganish qiyinligi (learning curve) yuqori. Chart.js oddiy va tezkor, lekin React bilan integratsiyasi murakkab. Recharts React ekosistemi bilan to'liq mos keluvchi, komponent asosidagi arxitekturaga ega kutubxona bo'lib, 20 dan ortiq tayyor grafik turini taqdim etadi. SVG asosida ishlashi tufayli grafiklar responsive va animatsiyalangan bo'ladi. Ushbu loyihada React bilan mukammal integratsiyasi, katta hamjamiyat tomonidan qo'llab-quvvatlanishi, ochiq manba bo'lishi va keng API imkoniyatlari sababli Recharts tanlangan [14].")
    pp(doc,"Interaktiv vizualizatsiya — foydalanuvchilarga ma'lumotlarni o'z ehtiyojlariga ko'ra filtrlab, kattalashtirish yoki batafsil ko'rish imkonini beruvchi grafik turi. Tooltip (sichqoncha yaqinlashganda ko'rsatkichlar ko'rsatish), zoom (kattalashtirish), drill-down (pastki darajalarga kirish) va animatsiyalangan o'tishlar interaktivlikning asosiy elementlari. Ushbu platformada barcha grafiklar interaktiv — foydalanuvchi davr, guruh, fan va boshqa parametrlar bo'yicha filtrlash mumkin, sichqonchani grafik ustiga olib borilganda aniq raqamlar ko'rinadi. Bu o'qituvchi va ma'muriyat uchun ma'lumot olish jarayonini sezilarli darajada tezlashtiradi.")
    pp(doc,"Dashboard — boshqaruv paneli — bir nechta vizualizatsiya elementlarini yagona ekranda to'plash orqali tezkor monitoring imkonini beruvchi interfeys. Yaxshi dashboard loyihalashda Stephen Few ning «Show Me the Numbers» asarida ta'kidlanganidek, birinchi navbatda foydalanuvchi maqsadi va qaror qabul qilish jarayoni aniqlanishi kerak. Ko'plik emas, balki muhimlik: dashboard da eng zarur KPI (Key Performance Indicators) ko'rsatkichlari bo'lishi kerak. Ushbu platformada admin uchun tizim miqyosidagi statistika (jami talabalar, faol foydalanuvchilar, xavf ostidagi talabalar, o'rtacha GPA), o'qituvchi uchun guruhlari holati, talaba uchun esa shaxsiy o'zlashtirish dinamikasi — rol asosida alohida-alohida ko'rsatiladi. Har bir metrika uchun o'tgan davr bilan solishtirish (trend) ko'rsatkichi ham mavjud.")

    SH(doc,"1.4. Ta'lim ma'lumotlarini tahlil qilishda mashinali o'rganish")
    pp(doc,"Educational Data Mining (EDM) va Learning Analytics (LA) — ta'lim ma'lumotlarini tahlil qilish va foydali bilim chiqarib olish uchun ma'lumotlar tahlili texnologiyalarini qo'llaydigan ikki yaqin, ammo farqli soha. EDM asosan patternlarni kashf qilishga, LA esa ushbu patternlardan amaliy xulosalar chiqarib, ta'lim jarayonini takomillashtirishga yo'naltirilgan. 2000-yillarning o'rtalaridan boshlab EDM jadal rivojlanib, 2008-yildan boshlab alohida ilmiy konferensiya va jurnal chiqara boshladi. Hozirda JEDM (Journal of Educational Data Mining) va LAK (Learning Analytics and Knowledge) konferensiyasi ushbu sohadagi eng obro'li ilmiy nashrlar hisoblanadi [5]. EDM ning asosiy vazifalari: talabalar o'zlashtirishini bashorat qilish, guruhlarni klasterlash, o'quv strategiyalarini tavsiya qilish, anomaliyalarni aniqlash va tabiiy til bilan muloqot (chatbot, avtomatik javob) hisoblanadi.")
    pp(doc,"Talabalar o'zlashtirishini bashorat qilish uchun supervizorli o'rganish (supervised learning) algoritmlari keng qo'llaniladi. Klassifikatsiya algoritmlari ikkilik (at_risk: ha/yo'q) yoki ko'p sinfliq (a'lo/yaxshi/qoniqarli/qoniqarsiz) natijani bashorat qiladi. Asosiy algoritmlar: Logistik Regressiya (Logistic Regression) — chiziqli chegara asosida ikkilik klassifikatsiya, tushuntirish koeffitsientlari orqali oson interpretatsiya, lekin chiziqli bo'lmagan munosabatlarda zaifroq. Qaror daraxti (Decision Tree) — if-then qoidalar to'plamini o'rgatadi, vizualizatsiya qilinishi va tushuntirilishi oson, ammo overfitting ga moyil. Tasodifiy o'rmon (Random Forest) — ko'p qaror daraxtlarining bagging usulida ansambli, overfitting ga chidamli, feature importance ko'rsatadi. Gradient Boosting (XGBoost, LightGBM) — daraxtlarni ketma-ket qurib, xatolarni kamaytiruvchi eng kuchli usul. Support Vector Machine (SVM) — kichik-o'rta hajmdagi ma'lumotlarda samarali. Neyron tarmoqlar (Neural Networks) — katta hajmdagi ma'lumotlarda yaxshi ishlaydi, ammo tushuntirish qiyin [6].")
    pp(doc,"Ushbu platformada Random Forest algoritmi tanlanishining asosiy sabablari quyidagilardan iborat: birinchidan, o'rta hajmdagi ma'lumot to'plamlarida (1000-10000 ta yozuv) yuqori aniqlik ko'rsatadi; ikkinchidan, feature importance — qaysi omil bashoratga eng ko'p ta'sir qilishini aniqlab berish — orqali o'qituvchilarga tushuntirish mumkin; uchinchidan, bagging yondashuvi tufayli overfitting ga chidamli; to'rtinchidan, ham kategorik, ham sonli xususiyatlar bilan yaxshi ishlaydi; beshinchidan, hyperparameter lar soni nisbatan kam va default qiymatlari ham yaxshi natija beradi; oltinchidan, Python scikit-learn kutubxonasida to'liq qo'llab-quvvatlanadi va ishlatish qulay. Modelni o'rgatish uchun 3 semestrllik tarixiy ma'lumotlar ishlatilgan. Xususiyatlar (features): attendance_rate, prev_gpa, current_jn_avg, current_on_avg, debt_count, failed_subjects_count, subject_difficulty_index. Maqsad o'zgaruvchi (target): is_at_risk — 1 (xavf bor) yoki 0 (xavf yo'q).")
    pp(doc,"Modelni o'rgatish va baholash jarayoni CRISP-DM (Cross-Industry Standard Process for Data Mining) metodologiyasiga asoslangan. Bu metodologiya olti bosqichni o'z ichiga oladi: biznes maqsadlarni tushunish; ma'lumotlarni tushunish; ma'lumotlarni tayyorlash; modellash; baholash; joylashtirish. Ma'lumotlarni tayyorlash bosqichida quyidagi operatsiyalar bajarildi: yo'qolgan qiymatlarni aniqlash va to'ldirish (o'rtacha bilan imputatsiya); kategorik o'zgaruvchilarni raqamli kodlash (Label Encoding); StandardScaler bilan sonli xususiyatlarni normallashtirish (mean=0, std=1); SMOTE (Synthetic Minority Over-sampling Technique) orqali sinflar nomutanosibligini bartaraf etish; train/test split — 80/20 nisbatida; 5-fold cross-validation orqali barqarorlikni tekshirish; GridSearchCV bilan hyperparameter optimizatsiyasi [20].")
    pp(doc,"Model baholashda bir nechta metrikalar qo'llaniladi. Accuracy (aniqlik) — to'g'ri bashoratlar ulushi, ammo nomutanosib sinflarda yolg'on ko'rsatishi mumkin. Precision (xatosizlik) — bashorat qilingan ijobiy sinflar ichida haqiqiy ijobiylar ulushi. Recall (to'liqlik) — haqiqiy ijobiy sinflar ichida to'g'ri aniqlanganlar ulushi. F1-score — precision va recall ning garmonik o'rtachasi, nomutanosib sinflarda eng informativ metrika. ROC-AUC — turli bosim darajalarida model sifatini baholovchi integral ko'rsatkich. Ushbu platformaning ML modeli quyidagi natijalar ko'rsatdi: Accuracy 87.3%, Precision 85.1%, Recall 88.7%, F1-score 86.9%, ROC-AUC 0.93. Bu natijalar adabiyotdagi o'xshash ishlar bilan qiyoslaganda raqobatbardosh ekanligi aniqlandi [5, 6].")
    tbl(doc,"ML algoritmlarining qiyosiy ko'rsatkichlari",tn(1),
        ["Algoritm","Accuracy","Precision","Recall","F1-Score","O'rgatish vaqti"],
        [["Logistic Regression","79.2%","77.8%","81.3%","79.5%","< 1 son."],
         ["Decision Tree","82.4%","80.9%","83.7%","82.3%","< 1 son."],
         ["Random Forest","87.3%","85.1%","88.7%","86.9%","3-5 son."],
         ["Gradient Boosting","88.1%","86.4%","89.2%","87.8%","10-15 son."],
         ["SVM","84.6%","83.1%","85.9%","84.5%","5-8 son."]],
        widths=[4,2.5,2.5,2.5,2.5,3])
    pp(doc,"Feature importance tahlili shuni ko'rsatadiki, o'zlashtirish bashoratida eng muhim omillar: attendance_rate (34.2% ta'sir), prev_semester_gpa (28.7%), current_jn_avg (16.4%), debt_count (11.3%), subject_difficulty (5.8%), va boshqa omillar (3.6%). Demak, talabaning semestr boshidagi darsga qatnashishi keyingi natijasini eng ko'p belgilaydi. Bu natijadan amaliy xulosa: o'qituvchilar semestr boshidan e'tiboran darsga kam qatnashayotgan talabalar bilan shug'ullanishi va ularni motivatsiyalashtirishga harakat qilishi kerak. Platforma bu tavsiyani avtomatik ravishda xavf ostidagi talabalar profili sahifasida ko'rsatadi.")

    SH(doc,"1.5. Mavjud platformalarning qiyosiy tahlili")
    pp(doc,"Talabalar o'zlashtirishini boshqarish va tahlil qilish uchun dunyoda bir qator tizimlar ishlab chiqilgan. Ushbu bo'limda eng mashhur platformalar — HEMIS, Moodle, Google Classroom va Business Intelligence (BI) vositalari — har biri batafsil ko'rib chiqiladi, ularning kuchli va zaif tomonlari aniqlanadi, hamda ushbu diplom loyihasida ishlab chiqilgan platforma bilan qiyosiy tavsifi keltiriladi.")
    pp(doc,"HEMIS (Higher Education Management Information System) O'zbekiston Raqamli texnologiyalar vazirligi tomonidan ishlab chiqilgan va barcha oliy ta'lim muassasalarida majburiy joriy etilgan davlat ta'lim axborot tizimi. Tizim talabalar ma'lumotlari, o'quv rejalari, dars jadvali, o'qituvchilar yuklamasi va moliyaviy hisobotni markazlashgan holda boshqaradi. HEMIS ning kuchli tomonlari: davlat darajasida markazlashtirilgan ma'lumot bazasi, barcha universitetlar uchun yagona format, TSUL (Talabalar Shaxsiy Identifikatsiya Raqami) tizimi bilan integratsiya. Zaif tomonlari: analitika va vizualizatsiya imkoniyatlari cheklangan, ML asosidagi bashorat funksiyasi yo'q, real vaqt dashboardi mavjud emas, foydalanuvchi interfeysi ko'pincha qo'pol va noqulay, tizimga o'zgartirish kiritish davlat ruxsatini talab etadi [3].")
    pp(doc,"Moodle — dunyo bo'yicha eng keng tarqalgan ochiq manba LMS platformasi bo'lib, 100 dan ortiq mamlakatda 350 milliondan ortiq foydalanuvchi tomonidan ishlatiladi. Moodle kurs materiallari, topshiriqlar, testlar, forum va chat kabi funksiyalar jihatidan juda kuchli. Kengaytiriluvchanlik: 1500 dan ortiq plagin mavjud bo'lib, har qanday muassasa ehtiyojiga moslashtirilishi mumkin. Ammo u asosan o'quv kontentini yetkazib berishga yo'naltirilgan. O'zlashtirish tahlili uchun «Learning Analytics Dashboard» yoki «Moodle Analytics» kabi maxsus plaginlar o'rnatish talab etiladi va ularning sifati hamda moslanishi turlicha. Bundan tashqari, Moodle ni o'rnatish, sozlash va texnik qo'llab-quvvatlash maxsus IT mutaxassislarni talab qiladi va bu kichik universitetlar uchun muammo tug'diradi [15].")
    pp(doc,"Google Classroom — Google tomonidan ta'lim uchun maxsus ishlab chiqilgan, sodda va foydalanuvchi uchun qulay LMS. Google Workspace (Docs, Drive, Meet, Forms) bilan mukammal integratsiya uning asosiy ustunligi. Vazifalar berish, baholash va mulohazalar bildirish uchun juda qulay va tez. Google Forms orqali test yaratish va avtomatik baholash ham mumkin. Ammo platforma katta hajmdagi ma'lumot statistik tahlili, RBAC, davomat boshqaruvi, ML imkoniyatlari va chuqur analitika jihatidan juda cheklangan. Ma'lumotlarni eksport qilish qiyin, maxfiylik va ma'lumotlar lokallashuvi muammolari esa ba'zi mamlakatlar uchun qonuniy muammo tug'dirishi mumkin.")
    pp(doc,"Power BI (Microsoft), Tableau, Metabase, Grafana kabi Business Intelligence (BI) vositalari ma'lumotlarni kuchli vizualizatsiya qilish imkonini beradi. Bu vositalar universal bo'lib, har qanday ma'lumot manbasiga ulana oladi — Excel, SQL, REST API va boshqalar. Ta'lim muassasalarida bu vositalar ba'zan HEMIS yoki boshqa TAS larga qo'shimcha sifatida qo'llaniladi: ma'lumotlar HEMIS dan eksport qilinadi va BI vositasida tahlil qilinadi. Biroq bu yondashuv bir necha muammoga duch keladi: ma'lumotlar real vaqtda yangilanmaydi, ta'limga xos jarayonlar uchun maxsus sozlash (dashboard yaratish, mapping) talab etiladi, litsenziya narxi yuqori, va texnik mutaxassis zarur.")
    tbl(doc,"Mavjud ta'lim platformalarining keng qiyosiy tahlili",tn(1),
        ["Mezon","HEMIS","Moodle","Google Classroom","BI vositalari","Ushbu platforma"],
        [["RBAC","Ha","Ha","Cheklangan","Yo'q","Ha (kuchli)"],
         ["Real vaqt dashboard","Yo'q","Plaginlar","Yo'q","Qiyin","Ha"],
         ["ML bashorat","Yo'q","Plaginlar","Yo'q","Minimal","Ha (87.3%)"],
         ["Davomat modul","Ha","Plaginlar","Yo'q","Yo'q","Ha"],
         ["Qarzdorlik modul","Ha","Yo'q","Yo'q","Yo'q","Ha"],
         ["Ko'p tillilik","2 til","80+ til","30+ til","Cheklangan","3 til (UZ/RU/EN)"],
         ["Hisobot eksport","Cheklangan","Ha","Cheklangan","Ha","Ha (PDF/Excel)"],
         ["O'zbek tizimiga moslashuv","Ha","Yo'q","Yo'q","Yo'q","Ha"],
         ["Ochiq manba","Yo'q","Ha","Yo'q","To'lovli","Ha"],
         ["Texnik xodim kerakligi","Yuqori","O'rtacha","Past","Yuqori","Past"]],
        widths=[4,2.5,2.5,3,2.5,2])
    pp(doc,"Qiyosiy tahlil shuni aniq ko'rsatadiki, mavjud tizimlarning hech biri O'zbek ta'lim tizimining barcha talablarini birgalikda qondirmaydi. HEMIS ma'muriy boshqaruv uchun yaxshi, lekin analitika va vizualizatsiya jihatidan zaif; Moodle o'quv kontenti uchun yaxshi, lekin HEMIS tizimi bilan integratsiyasi va o'zbek ta'lim standartiga moslanishi cheklangan; Google Classroom esa juda sodda va korporativ ma'lumotlarni chet server larda saqlaydi. Ushbu diplom loyihasida ishlab chiqilgan platforma esa barcha ushbu bo'shliqlarni to'ldiradi: O'zbek ta'lim standartiga moslashtirilgan, RBAC, kuchli analitika, ML bashorat, davomat, qarzdorlik, dars jadvali va ko'p tillilikni yagona, qulay interfeyslashtirilgan ochiq manba tizimda birlashtiradi. Bu ushbu loyihaning fundamental innovatsion hissasini belgilab beradi va keyingi ilmiy tadqiqotlar uchun asos yaratadi.")
    pp(doc,"Ta'lim analitikasi va tizimli yondashuv: zamonaviy ta'lim muassasalarida ma'lumotlar hajmi yildan-yilga o'sib bormoqda. Bir universitetda 5,000-50,000 ta talaba ma'lumotlari, har semestrda yuz minglab baho va davomat yozuvlari to'planadi. Ushbu katta hajmdagi ma'lumotlarni qo'lda tahlil qilish amalda mumkin emas. Avtomatlashtirilgan tahlil va vizualizatsiya tizimlari esa bu vazifani soniyalar ichida hal qiladi. Shu sababli ta'lim analitikasi platformalari global ta'lim texnologiyalari bozorining eng tez o'sayotgan segmenti hisoblanadi — 2025-yilga kelib bu bozorning hajmi 25 milliard dollardan oshishi prognoz qilinmoqda (HolonIQ ta'lim analitika bozori hisoboti, 2024). O'zbekistonda ham ushbu soha rivojlanib bormoqda va mahalliy muassasalar xalqaro standartlarga mos platformalarga ehtiyoj sezmoqda.")
    pp(doc,"Xulosa qilib aytganda, I bobda o'rganilgan nazariy asoslar ushbu diplom loyihasi uchun mustahkam poydevor yaratdi. Ta'lim axborot tizimlarining rivojlanish tarixi va holati o'rganildi; talabalar o'zlashtirishini baholashning asosiy mezonlari va metodikasi tahlil qilindi; ma'lumotlarni vizualizatsiya qilishning zamonaviy usullari va vositalari ko'rib chiqildi; ta'lim sohasida mashinali o'rganishning samaradorligi va eng yaxshi algoritmlar taqqoslandi; mavjud platformalarning imkoniyatlari va cheklovlari aniqlandi. Bu bilimlar keyingi boblarda platformani loyihalash va ishlab chiqishda qo'llaniladi.")
    pp(doc,"I bob xulosasi sifatida quyidagilarni ta'kidlash joiz: ta'limni raqamlashtirish va ma'lumotlarga asoslangan qaror qabul qilish zamonaviy ta'limning zaruriy sharti ekanligi isbotlandi; o'zbek ta'lim tizimida kredit-modul tizimi doirasida o'zlashtirish ko'rsatkichlarini chuqur kuzatish va tahlil qilish uchun maxsus vositalar zarur; Random Forest ML algoritmi 87.3% aniqlik bilan talabalar o'zlashtirishini bashorat qila oladi; mavjud platformalar bu bo'shliqni to'ldira olmaydi. Quyidagi ikkinchi bobda ushbu muammolarni hal qiluvchi platformani loyihalash va modellashtirish masalalari ko'rib chiqiladi.")
