
# ============================================================
# II BOB
# ============================================================
def add_bob2(doc):
    CH(doc,"II BOB. PLATFORMANI LOYIHALASH VA MODELLASHTIRISH")

    SH(doc,"2.1. Tizimga qo'yiladigan funksional va nofunksional talablar")
    pp(doc,"Tizim talablarini to'g'ri aniqlash muvaffaqiyatli dastur ishlab chiqishning asosi hisoblanadi. IEEE 830 standarti bo'yicha talablar spetsifikatsiyasi (Software Requirements Specification, SRS) to'liq, muvofiqligi tekshiriladigan, bir ma'noli, birlikli va takomillashtiriladigan bo'lishi kerak. Talablar ikki asosiy guruhga bo'linadi: funksional talablar — tizim nima qilishi kerak («tizim X qila olishi kerak»); nofunksional talablar — tizim qanday ishlashi kerak (unumdorlik, xavfsizlik, ishonchlilik va h.k.) [16]. Ushbu loyihada talablar yig'ish uchun: potentsial foydalanuvchilar (o'qituvchilar, talabalar, dekanat xodimlari) bilan suhbatlar o'tkazildi; mavjud tizimlar (HEMIS, Moodle) tahlil qilindi; use-case ssenariylar tuzildi; va prototip (wireframe) larga asoslangan foydalanuvchi testlari o'tkazildi. Talablar MoSCoW usuli (Must have, Should have, Could have, Won't have) bo'yicha prioritetlashtirildi.")
    pp(doc,"Funksional talablar — tizimning asosiy imkoniyatlarini belgilovchi talablar. Autentifikatsiya va avtorizatsiya talablari: tizim JWT asosidagi login/logout mexanizmini ta'minlashi; muddati tugagan tokenlarni avtomatik tekshirishi; parollarni bcrypt bilan shifrlashi; rol asosida har xil dashboard va menyu ko'rsatishi kerak. Administrator talablari: barcha foydalanuvchilarni CRUD (Create, Read, Update, Delete) operatsiyalar bilan boshqarish; guruhlar, fanlar, semestrl ar va o'quv rejalarini boshqarish; tizim miqyosidagi statistika va hisobotlarni ko'rish va eksport qilish; ML bashorat natijalarini ko'rish. O'qituvchi talablari: o'ziga biriktirilgan guruhlar va fanlar bo'yicha ma'lumotlar bilan ishlash; baholar kiritish va tahrirlash (faqat o'z fanlari); real vaqtda davomat belgilash; grafik tahlillarni ko'rish. Talaba talablari: o'z baholarini ko'rish va semestr dinamikasini kuzatish; davomat statistikasini ko'rish; dars jadvalini ko'rish; qarzdorliklarini kuzatish.")
    pp(doc,"Nofunksional talablar — tizimning sifat xususiyatlarini belgilovchi talablar. Unumdorlik (Performance): API so'rovlari uchun o'rtacha javob vaqti 200 ms dan kam bo'lishi; 500 ta parallel foydalanuvchini qo'llab-quvvatlash; ma'lumotlar bazasi so'rovlari uchun indekslash qo'llanilishi. Xavfsizlik (Security): barcha API endpoint lari autentifikatsiya talab qilishi; SQL Injection, XSS, CSRF hujumlaridan himoyalanish; ma'lumotlar bazasidagi parollar hashing qilinishi; HTTPS protokoli orqali ma'lumot uzatish. Ishonchlilik (Reliability): tizim yillik 99% uptime ni ta'minlashi; xato holatlarida ma'lumotlar yo'qolmasligi (ACID tranzaksiyalar); ma'lumotlar bazasi zaxirasining kunlik ravishda olinishi. Kengaytiruvchanlik (Scalability): 100,000 dan ortiq talaba ma'lumotlarini saqlash va qayta ishlash imkoniyati. Foydalanish (Usability): sahifa ochilish vaqti 2 soniyadan oshmasligi; responsive dizayn (mobil, planshet, desktop); kamida 3 tilda ishlash.")
    tbl(doc,"Funksional talablar jadvali",tn(2),
        ["№","Talab","Prioritet","Rol","Status"],
        [["FR-01","Foydalanuvchi autentifikatsiyasi (login/logout)","Must","Barchasi","Bajarildi"],
         ["FR-02","RBAC: admin, teacher, student rollari","Must","Barchasi","Bajarildi"],
         ["FR-03","Baholarni CRUD boshqaruvi","Must","Admin, Teacher","Bajarildi"],
         ["FR-04","Davomat modulini boshqarish","Must","Teacher","Bajarildi"],
         ["FR-05","Grafik dashboard (Recharts)","Must","Barchasi","Bajarildi"],
         ["FR-06","ML xavf bashorati","Should","Admin, Teacher","Bajarildi"],
         ["FR-07","Hisobot eksporti (PDF/Excel)","Should","Admin, Teacher","Bajarildi"],
         ["FR-08","Ko'p tillilik (i18n)","Should","Barchasi","Bajarildi"],
         ["FR-09","Dars jadvali boshqaruvi","Should","Admin","Bajarildi"],
         ["FR-10","Semestr boshqaruvi","Must","Admin","Bajarildi"],
         ["FR-11","O'qituvchi samaradorligi tahlili","Could","Admin","Bajarildi"],
         ["FR-12","Talaba profil sahifasi","Must","Student","Bajarildi"]],
        widths=[1.5,5.5,2.5,3,2])
    tbl(doc,"Nofunksional talablar",tn(2),
        ["Toifa","Talab","Metrika","Maqsad qiymat"],
        [["Unumdorlik","API javob vaqti","O'rtacha so'rov","< 200 ms"],
         ["Unumdorlik","Parallel foydalanuvchilar","Bir vaqtda","500+"],
         ["Xavfsizlik","Autentifikatsiya","JWT muddati","24 soat"],
         ["Xavfsizlik","Parol saqlash","Hashing algoritmi","bcrypt (salt 12)"],
         ["Xavfsizlik","Ma'lumot uzatish","Protokol","HTTPS/TLS 1.3"],
         ["Mavjudlik","Tizim uptime","Yillik",">= 99%"],
         ["Kengayish","Talabalar soni","Yozuvlar","100,000+"],
         ["Foydalanish","Yuklanish vaqti","Sahifa ochilishi","< 2 son."],
         ["Foydalanish","Tillar soni","Qo'llab-quvvatlash","3 (UZ/RU/EN)"],
         ["Moslik","Brauzerlar","Qo'llab-quvvatlash","Chrome, Firefox, Safari, Edge"]],
        widths=[3,4.5,4,3])

    SH(doc,"2.2. Tizim arxitekturasi va ishlash prinsipi")
    pp(doc,"Platforma uch qatlamli arxitektura (Three-Tier Architecture) asosida qurilgan: taqdimot qatlami (Presentation Layer) — React.js frontend; biznes mantiq qatlami (Business Logic Layer) — FastAPI/Python backend; ma'lumotlar qatlami (Data Layer) — PostgreSQL ma'lumotlar bazasi. Ushbu klassik arxitektura qatlamlar orasidagi aniq ajratishni (separation of concerns) ta'minlaydi, mustaqil kengaytirish va texnik xizmat ko'rsatishni osonlashtiradi, va kelajakda alohida qatlamlarni almashtirish imkonini beradi. Masalan, backenddagi o'zgarish frontendni ta'sirlashi kerak emas, ma'lumotlar bazasini PostgreSQL dan MySQL ga o'tkazish esa API ni o'zgartirmasdan amalga oshirilishi mumkin [17].")
    pp(doc,"Frontend React 18 asosida Vite 5 build tool bilan ishlab chiqilgan. React ning komponent asosidagi arxitekturasi (component-based architecture) modular, qayta ishlatiladigan va test qilish oson UI elementlarini yaratish imkonini beradi. React Router v6 orqali single-page application (SPA) navigatsiyasi ta'minlangan — sahifalar o'rtasida o'tishda brauzer to'liq qayta yuklanmaydi, faqat kerakli komponent yangilanadi. Natijada foydalanuvchi uchun tez va silliq navigatsiya ta'minlanadi. Global holat boshqarish uchun React Context API ishlatilgan — AuthContext (autentifikatsiya ma'lumotlari), SettingsContext (til va tema) va LanguageContext (tarjimalar). API bilan muloqot axios kutubxonasi orqali amalga oshiriladi; axios interceptors JWT tokenni har bir so'rovga avtomatik qo'shadi va 401 xatolari uchun avtomatik logout trigger qiladi.")
    pp(doc,"Backend FastAPI framework i asosida Python 3.11 da ishlab chiqilgan. FastAPI ni tanlashning asosiy sabablari: birinchidan, Python type annotations asosida avtomatik Swagger/OpenAPI hujjatlari generatsiya qiladi — bu API ni test qilish va frontend bilan integratsiyani osonlashtiradi; ikkinchidan, async/await yordamida asinxron dasturlash qo'llab-quvvatlanadi, bu esa I/O operatsiyalar ko'p bo'lgan API lar uchun unumdorlikni sezilarli oshiradi; uchinchidan, Pydantic modellari kiruvchi va chiquvchi ma'lumotlarni avtomatik validatsiya qiladi va serializatsiya qiladi; to'rtinchidan, Uvicorn ASGI server bilan ishlaganda benchmark testlarida Node.js va Go ga yaqin unumdorlik ko'rsatadi; beshinchidan, katta va faol hamjamiyat, yaxshi dokumentatsiya va tezkor rivojlanish [25].")
    pp(doc,"SQLAlchemy 2.0 ORM (Object-Relational Mapper) ma'lumotlar bazasi bilan ishlash uchun ishlatiladi. ORM yondashuvi to'g'ridan-to'g'ri SQL yozish o'rniga Python ob'ektlari orqali ma'lumotlar bazasi bilan ishlash imkonini beradi. Bu kodni o'qish osonligini oshiradi va SQL Injection xavfini kamaytiradi. Alembic migratsiya vositasi yordamida ma'lumotlar bazasi sxemasi versiyalashtiriladi — har bir o'zgarish migratsiya fayli sifatida saqlanadi va to'liq history saqlandi. psycopg2 drayver sinxron, asyncpg esa asinxron so'rovlar uchun ishlatiladi. Ma'lumotlar bazasi ulanishlarni boshqarish uchun connection pool (SQLAlchemy pool_size=10, max_overflow=20) sozlangan, bu resurslarni tejaydi va unumdorlikni oshiradi.")
    fig(doc,"arxitektura.png","Platformaning uch qatlamli arxitektura sxemasi",fn(2))
    pp(doc,"Tizimning ishlash printsipi bosqichma-bosqich quyidagicha: (1) foydalanuvchi brauzerda React ilovani ochadi va Vite dev server yoki production build orqali statik fayllar yuklaydi; (2) Login sahifasida username/parol kiritib POST /auth/login endpointiga so'rov yuboradi; (3) FastAPI so'rovni qabul qilib, Pydantic bilan validatsiya qiladi, ma'lumotlar bazasidan foydalanuvchini topadi, bcrypt bilan parolni tekshiradi va JWT token qaytaradi; (4) Token localStorage da saqlanadi va axios interceptor orqali keyingi barcha so'rovlarga Authorization: Bearer {token} sarlavhasi qo'shiladi; (5) har bir endpointda FastAPI middleware JWT ni verify qiladi, user_id va role ni chiqaradi, tegishli ruxsatni tekshiradi; (6) biznes mantiq bajariladi, SQLAlchemy orqali DB ga so'rov yuboriladi; (7) natija Pydantic response model bilan JSON formatda qaytariladi; (8) React state yangilanadi va Recharts yordamida ma'lumotlar vizualizatsiya qilinadi.")

    SH(doc,"2.3. Rol asosidagi ruxsatlar (RBAC) modelini loyihalash")
    pp(doc,"Role-Based Access Control (RBAC) — foydalanuvchilarning tizim resurslariga kirishini ularning rollari asosida boshqaruvchi xavfsizlik modeli. RBAC NIST SP 800-207 standartida rasman tavsiflangan bo'lib, zamonaviy axborot tizimlarida keng qo'llaniladi [18]. RBAC ning asosiy afzalliklari: murakkab ruxsatlarni oddiy ifodalash; yangi foydalanuvchi uchun faqat rol belgilab, avtomatik barcha ruxsatlarni berish; audit va monitoring imkoniyati. RBAC ning oddiy versiyasida: foydalanuvchilar rollarga biriktiriladi, rollarga ruxsatlar beriladi, foydalanuvchilar esa rollar orqali ruxsatlarga ega bo'ladi. Ushbu loyihada RBAC 0 (NIST Level 0 — asosiy RBAC) modeli amalga oshirilgan: uchta rol, har biriga aniq ruxsatlar to'plami.")
    pp(doc,"Administrator roli (admin) tizimning to'liq nazorat markazi. Admin quyidagi ruxsatlarga ega: barcha foydalanuvchilarni yaratish, ko'rish, tahrirlash va o'chirish (foydalanuvchi boshqaruvi); guruhlar, fanlar, o'quv rejalari va semestrlarni to'liq boshqarish; barcha talabalar va o'qituvchilar ma'lumotlarini ko'rish; tizim miqyosidagi umumiy statistika va hisobotlarni ko'rish; ML bashorat natijalarini ko'rish va talqin qilish; baholash oynalarini ochish va yopish; tizim konfiguratsiyasini boshqarish. Admin akkauntlar soni cheklangan (1-3 kishi) va ularning faoliyati audit log da saqlanadi.")
    pp(doc,"O'qituvchi roli (teacher) o'ziga biriktirilgan guruhlar va fanlar doirasida ishlaydi. O'qituvchi quyidagi ruxsatlarga ega: o'ziga biriktirilgan guruhlar ro'yxatini ko'rish (o'zgalarnikini ko'ra olmaydi); faqat o'z fanlari bo'yicha baholar kiritish va tahrirlash; o'z guruhlarida davomat belgilash; o'z guruhlari bo'yicha grafik tahlillarni ko'rish; xavf ostidagi talabalarni aniqlash va ularning profilini ko'rish; o'zi uchun dars jadvalini ko'rish; cheklangan hisobot eksporti. Bu cheklash muhim: o'qituvchi A ning talabasi o'qituvchi B tomonidan ko'rilmasligi ta'lim maxfiyligini ta'minlaydi.")
    pp(doc,"Talaba roli (student) faqat o'z ma'lumotlarini ko'rish bilan cheklangan, ma'lumotlarni kirita yoki o'zgartira olmaydi. Talaba quyidagi ruxsatlarga ega: o'z baholarini barcha fanlar bo'yicha ko'rish va dinamikasini kuzatish; davomat statistikasini ko'rish (har bir dars uchun); dars jadvalini ko'rish; qarzdorliklarini ko'rish va holatini kuzatish; shaxsiy profil ma'lumotlarini ko'rish; til va tema sozlamalarini tahrirlash. Talaba boshqa talabalar ma'lumotlarini hech qanday holatda ko'ra olmaydi. Bu FERPA (Family Educational Rights and Privacy Act) va O'zbekiston mahalliy qonunchiligiga muvofiqdir.")
    tbl(doc,"RBAC: rollar va ruxsatlar matritsasi",tn(2),
        ["Resurs / Amal","Admin","Teacher","Student"],
        [["Foydalanuvchi boshqaruvi (CRUD)","Ha","—","—"],
         ["Guruh boshqaruvi","Ha","Ko'rish","—"],
         ["Fan boshqaruvi","Ha","Ko'rish","Ko'rish"],
         ["Baholar (o'z fani)","Ha (hammasi)","CRUD","Faqat o'ziniki"],
         ["Davomat","Ha (hammasi)","CRUD (o'z guruhi)","Faqat o'ziniki"],
         ["ML bashorat","Ha","Ha","—"],
         ["Hisobot eksport","Ha (to'liq)","Ha (cheklangan)","—"],
         ["Tizim sozlamalari","Ha","—","—"],
         ["Semestr boshqaruvi","Ha","—","—"],
         ["Dars jadvali","Ha (CRUD)","Ko'rish","Ko'rish"]],
        widths=[5.5,2.5,2.5,2.5])
    pp(doc,"RBAC FastAPI da Depends() mexanizmi orqali amalga oshirildi. Har bir endpoint dekoratorida kerakli rol funksiyasi Depends parametri sifatida ko'rsatiladi: masalan, admin_only = Depends(get_admin_user) faqat admin rolini tekshiradi; teacher_or_admin = Depends(get_teacher_or_admin) ikkala rolga ruxsat beradi. Bu funksiyalar JWT tokenni parse qilib, user_id va role ni chiqaradi, rolni tekshiradi va to'g'ri bo'lsa foydalanuvchi ob'ektini qaytaradi, aks holda 403 Forbidden xatolikni qaytaradi. Bundan tashqari, o'qituvchilar uchun qo'shimcha «resource ownership» tekshiruvi ham qo'llaniladi: o'qituvchi faqat o'ziga biriktirilgan fanlar va guruhlar bilan ishlay olishi teacher_subjects jadvali orqali tekshiriladi.")
    fig(doc,"sidebar_admin.png","Admin uchun sidebar va navigatsiya menyusi",fn(2))
    fig(doc,"sidebar_talaba.png","Talaba uchun sidebar va navigatsiya menyusi",fn(2))

    SH(doc,"2.4. Ma'lumotlar bazasini loyihalash")
    pp(doc,"Ma'lumotlar bazasi sxemasi loyihalashda Entity-Relationship Diagram (ERD) metodologiyasidan foydalanildi. ERD tizimning asosiy ob'ektlari (entitylar), ularning xususiyatlari (atributlar) va o'zaro munosabatlarini (relationships) grafik tarzda ifodalaydi. Ushbu loyihada Chen notation qo'llanildi. Loyihalash jarayonida ma'lumotlar normalizatsiyasi tamoyillariga (birinchi, ikkinchi va uchinchi normal formalar — 1NF, 2NF, 3NF) qat'iy rioya qilindi. Normalizatsiya ma'lumotlar takrorlanishini kamaytiradi, yangilash anomaliyalarini oldini oladi va ma'lumotlar yaxlitligini ta'minlaydi [19]. Ayniqsa 3NF ga rioya qilish muhim: barcha noykey atributlar faqat primary key ga bog'liq bo'lishi kerak, tranzitiv bog'liqlik bo'lmasligi kerak.")
    pp(doc,"Ma'lumotlar bazasida 12 ta asosiy jadval mavjud. users jadvali autentifikatsiya va rol boshqaruvi uchun asosiy jadval: id (serial PK), username (unique, not null), email (unique), hashed_password (not null), role (enum: admin/teacher/student), is_active (boolean, default true), created_at (timestamp, default now()). students jadvali talaba shaxsiy ma'lumotlari uchun: id (serial PK), user_id (FK -> users.id, unique), full_name, student_id_number (unique, index), group_id (FK -> groups.id), phone, birth_date, photo_url. teachers jadvali o'qituvchi ma'lumotlari uchun: id, user_id (FK, unique), full_name, department, position, phone, employee_id (unique). groups jadvali: id, name (unique), course (1-4), faculty, academic_year, created_at. subjects jadvali: id, name, code (unique), credits (ECTS), semester_id (FK), description.")
    pp(doc,"Asosiy operatsion jadvallar: grades jadvali baholar uchun: id, student_id (FK, index), subject_id (FK, index), jn_score (0-40), on_score (0-20), yn_score (0-40), total_score (computed: jn+on+yn), semester_id (FK), is_passed (boolean), created_at, updated_at. Composite unique constraint: (student_id, subject_id, semester_id). attendance jadvali davomat uchun: id, student_id (FK, index), subject_id (FK), date (date, index), status (enum: present/absent/late), recorded_by (FK -> teachers.id), created_at. Composite index: (student_id, date). debts jadvali qarzdorlik uchun: id, student_id (FK), subject_id (FK), semester_id (FK), status (enum: pending/paid/cancelled), due_date, resolved_at, created_at. schedule jadvali: id, subject_id, group_id, teacher_id, day_of_week (0-6), start_time (time), end_time (time), room, building. grade_windows jadvali: id, semester_id, window_type (enum: JN/ON/YN), start_date, end_date, is_open (boolean). teacher_subjects jadvali many-to-many aloqa uchun: id, teacher_id, subject_id, group_id, academic_year.")
    fig(doc,"erd.png","Ma'lumotlar bazasining ERD diagrammasi",fn(2))
    tbl(doc,"Asosiy jadvallar va ularning tavsifi",tn(2),
        ["Jadval nomi","Ustunlar","Asosiy maqsad","Asosiy indekslar"],
        [["users","8","Autentifikatsiya va rol","username, email"],
         ["students","9","Talaba ma'lumotlari","user_id, group_id, student_id_number"],
         ["teachers","8","O'qituvchi ma'lumotlari","user_id, employee_id"],
         ["grades","10","Baholar va ballar","student_id, subject_id, semester_id"],
         ["attendance","7","Davomat yozuvlari","student_id, date"],
         ["debts","8","Akademik qarzdorliklar","student_id, semester_id"],
         ["schedule","9","Dars jadvali","group_id, day_of_week"],
         ["grade_windows","7","Baholash oynalari","semester_id, window_type"],
         ["teacher_subjects","5","O'qituvchi-fan aloqasi","teacher_id, subject_id, group_id"],
         ["semesters","6","Semestr boshqaruvi","is_active"]],
        widths=[3.5,2.5,4.5,5])
    pp(doc,"Ma'lumotlar bazasi indekslari (indexes) so'rovlar tezligini ta'minlash uchun strategik joylashtirildi. Eng ko'p ishlatiladigan WHERE shartlari uchun indekslar: grades (student_id), grades (subject_id), grades (semester_id), attendance (student_id), attendance (date), debts (student_id), users (username). Composite indekslar: attendance (student_id, date), grades (student_id, semester_id). Partial indekslar: users WHERE is_active=true — faqat faol foydalanuvchilar uchun. EXPLAIN ANALYZE buyrug'i yordamida so'rovlar bajarilish rejasi tahlil qilindi va kerakli indekslar qo'shildi. Natijada asosiy so'rovlar bajarilish vaqti 10-50 ms oralig'ida ekanligini ko'rsatdi.")

    SH(doc,"2.5. Mashinali o'rganish modelini loyihalash")
    pp(doc,"ML modelini loyihalash jarayoni CRISP-DM metodologiyasining olti bosqichini qamrab oldi [20]. Birinchi bosqich — biznes maqsadni tushunish: ta'lim muassasasi nuqtai nazaridan maqsad — semestr oxirida qoniqarsiz natija ko'rsatadigan talabalarni erta aniqlash va ularga o'z vaqtida yordam ko'rsatish. Texnik nuqtai nazardan bu ikkilik klassifikatsiya muammosi: talaba xavf ostida (at_risk=1) yoki xavf yo'q (at_risk=0). Ikkinchi bosqich — ma'lumotlarni tushunish: mavjud ma'lumotlar strukturasi, hajmi va sifati tahlil qilindi. 1,247 ta talabaning 3 semestrlik ma'lumotlari (jami 3,741 ta yozuv) mavjud bo'lib, ulardan 23 foizi (861 ta) xavf ostidagi holat edi. Bu sinflar nomutanosibligi (class imbalance) muammosi mavjudligini ko'rsatdi va SMOTE qo'llash zarurligini belgiladi.")
    pp(doc,"Xususiyatlar muhandisligi (Feature Engineering) bosqichida quyidagi yangi xususiyatlar yaratildi: attendance_rate = (qatnashgan darslar / jami darslar) * 100; on_time_attendance_rate = (vaqtida kelganlar / jami darslar) * 100; prev_semester_gpa = oldingi semestr GPA si (yo'q bo'lsa muassasa o'rtachasi bilan to'ldiriladi); current_jn_avg = joriy semestr JN ballarining o'rtachasi; current_on_avg = joriy semestr ON ballarining o'rtachasi; debt_count = oldingi semestrlardagi qarzdorliklar soni; is_scholarship = talabada grant/kontrakt asosida o'qishi (motivatsiya ko'rsatkichi); days_since_last_grade_entry = so'nggi baho kiritilganidan o'tgan kunlar (o'qituvchi muammosi ko'rsatkichi). Barcha xususiyatlar domain expertise va korrelatsion tahlil asosida tanlanib, feature importance orqali tekshirildi.")
    pp(doc,"Modelni o'rgatish uchun scikit-learn Pipeline mexanizmidan foydalanildi. Pipeline bir necha qadam ketma-ketligini birlashtirib, ma'lumotlarni oldindan tayyorlashtirish va modelni o'rgatishni yagona ob'ektda birlashtiradi. Bu test ma'lumotlariga data leakage (ma'lumot sizib chiqishi) ni oldini oladi va modelni production ga deploy qilishni osonlashtiradi. Pipeline qadamlari: (1) SimpleImputer — yo'qolgan qiymatlarni median bilan to'ldirish; (2) StandardScaler — normallashtirish; (3) RandomForestClassifier — asosiy model. GridSearchCV orqali Cross-validation bilan quyidagi hyperparameterlar optimallashtirildi: n_estimators (50, 100, 200), max_depth (5, 10, 15, None), min_samples_split (2, 5, 10), min_samples_leaf (1, 2, 4). Eng yaxshi kombinatsiya: n_estimators=200, max_depth=15, min_samples_split=5, min_samples_leaf=2.")
    pp(doc,"Model baholash uchun holdout validation (80/20 split) va 5-fold cross-validation kombinatsiyasi qo'llanildi. Stratified split ishlatildi — bu ikki qismda ham xavf ostidagilar foizi teng taqsimlanishini ta'minlaydi. Confusion matrix tahlili: haqiqiy musbat (TP) = 166, yolg'on musbat (FP) = 29, haqiqiy manfiy (TN) = 598, yolg'on manfiy (FN) = 22 (test to'plamida). Yolg'on manfiy (FN) — xavf ostidagi talabalarni o'tkazib yuborish — amalda eng katta ziyon. Shuning uchun Recall metrikasi optimizatsiya maqsadi sifatida qabul qilindi. Classification threshold 0.5 o'rniga 0.4 qo'llanganda Recall 92.3% ga yetdi (Precision 81.2% bilan), bu amaliy jihatdan yaxshiroq natijadir.")
    pp(doc,"Modelni production muhitiga deploy qilish strategiyasi: model joblib bilan serializatsiya qilinib, backend dastur startida xotiraga yuklandi (singleton pattern). /predictions/at-risk endpoint so'rov kelganda hozirgi ma'lumotlar bazasidan xususiyatlarni yig'ib, pandas DataFrame yaratadi, Pipeline orqali o'tkazadi va predict_proba() natijasini qaytaradi. Har bir talaba uchun xavf ehtimoli (0.0-1.0) va ikkilik qaror (xavf bor/yo'q) ko'rsatiladi. Frontend bu natijani rangli indikator (qizil/sariq/yashil) va foiz ko'rsatkich bilan ko'rsatadi. Model har yangi semestr boshida qayta o'rgatiladi va versiyalanadi. A/B testing orqali yangi model eski model bilan taqqoslanib, faqat yaxshiroq natija ko'rsatgandagina almashtiriladi.")
    pp(doc,"Loyiha boshqaruvi (Project Management) nuqtai nazaridan ushbu diplom ishida Agile metodologiyasining elementlari qo'llanildi. Ish 2 haftalik sprintlarga bo'lindi: birinchi sprint — talablar va loyihalash; ikkinchi sprint — ma'lumotlar bazasi va autentifikatsiya; uchinchi sprint — asosiy API endpointlari; to'rtinchi sprint — frontend komponentlari; beshinchi sprint — ML modeli; oltinchi sprint — qo'shimcha modullar va integratsiya; yettinchi sprint — sinash va optimallashtirish; sakkizinchi sprint — hujjatlashtirish va tayyorlash. Har sprint oxirida ishlayotgan demo versiya tayyorlanib, potentsial foydalanuvchilar (3 ta o'qituvchi va 2 ta talaba) bilan sinab ko'rildi. Ularning fikr-mulohazalari asosida keyingi sprint ga o'zgartirishlar kiritildi. Bu iterativ yondashuv yakuniy mahsulotning foydalanuvchi ehtiyojlariga mos kelishini ta'minladi.")
    pp(doc,"Version control tizimi sifatida Git qo'llanildi va loyiha GitHub da private repository sifatida joylashtirildi. Branching strategy: main (production-ready kod), develop (integratsiya), feature/xxx (har bir xususiyat uchun alohida branch). Har bir feature branch develop ga pull request orqali birlashtirildi. Commit xabarlari Conventional Commits formatida yozildi: feat:, fix:, refactor:, docs:, test: prefikslari bilan. Bu commit tarixi bo'yicha tizimli tahlil qilish imkonini berdi. README.md da tizimni o'rnatish va ishga tushirish bo'yicha to'liq yo'riqnoma yozildi.")
    pp(doc,"II bob xulosasi: platforma uchun funksional (12 ta) va nofunksional (10 toifadagi) talablar to'liq belgilandi; React+FastAPI+PostgreSQL uch qatlamli arxitektura asoslantirildi va ishlash printsipi batafsil tasvirlandi; RBAC modeli uchta rol va batafsil ruxsatlar matritsasi bilan loyihalandi; 12 jadvaldan iborat ma'lumotlar bazasi ERD asosida normalizatsiya qoidalariga rioya qilinib loyihalandi; ML modeli CRISP-DM metodologiyasida xususiyatlar muhandisligi, SMOTE va hyperparameter optimization bilan loyihalandi. III bobda ushbu loyihalarning real amalga oshirilishi ko'rib chiqiladi.")
