
# ============================================================
# III BOB
# ============================================================
def add_bob3(doc):
    CH(doc,"III BOB. PLATFORMANI ISHLAB CHIQISH VA SAMARADORLIGINI BAHOLASH")

    SH(doc,"3.1. Dasturiy vositalar va texnologiyalarni tanlash")
    pp(doc,"To'g'ri texnologiya stekini tanlash loyihaning muvaffaqiyatiga bevosita ta'sir qiladi. Texnologiya tanlashda bir necha mezonlar hisobga olindi: jamoa tajribasi va bilimi; texnologiyaning etuklik darajasi, barqarorligi va hamjamiyat faolligi; unumdorlik va kengaytiruvchanlik; litsenziya (ochiq manba afzalligi); ekosistema boyligi (kutubxonalar, vositalar); deployment va deployment osonligi. Har bir asosiy texnologiya uchun alternativlar ko'rib chiqildi va optimal tanlov asoslandi. Masalan, frontend uchun React, Vue.js va Angular ko'rib chiqildi — React ning keng ekosistemi, komponent arxitekturasi, virtual DOM unumdorligi va developer demand jihatidan afzalligi aniqlandi. Backend uchun FastAPI, Django, Flask va Node.js ko'rib chiqildi — FastAPI ning async imkoniyatlari, avtomatik hujjatlar va type safety afzalligi tanlovni belgiladi [17].")
    tbl(doc,"Tanlangan texnologiyalar va asoslanishi",tn(3),
        ["Texnologiya","Versiya","Maqsad","Tanlash sababi"],
        [["React.js","18.3","Frontend UI framework","Komponent arxitektura, katta ekosistema, virtual DOM"],
         ["Vite","5.2","Build tool","Tez HMR, optimallashtirilgan bundle, ES modules"],
         ["Tailwind CSS","3.4","UI stillashtirish","Utility-first, tez prototiplash, responsive"],
         ["Recharts","2.12","Grafik kutubxona","React integratsiyasi, SVG, animatsiya, 20+ grafik turi"],
         ["React Router","6.23","Frontend routing","SPA navigatsiya, lazy loading, nested routes"],
         ["i18next","26.3","Ko'p tillilik (i18n)","Keng qo'llab-quvvatlash, namespace, interpolatsiya"],
         ["axios","1.7","HTTP client","Interceptors, JWT auto-inject, error handling"],
         ["lucide-react","0.383","Ikonlar kutubxonasi","Engil, consistent, ko'p ikonlar"],
         ["FastAPI","0.111","Backend API framework","Tezlik, async, Swagger auto, type hints"],
         ["SQLAlchemy","2.0","ORM","Deklarativ model, migratsiya, query builder"],
         ["Alembic","1.13","DB migratsiya","Version control for schema, rollback"],
         ["Pydantic","2.7","Ma'lumot validatsiya","Avtomatik validatsiya, serialization"],
         ["PostgreSQL","16","Ma'lumotlar bazasi","ACID, murakkab so'rovlar, JSON, kengaytiriluvchanlik"],
         ["scikit-learn","1.3","ML modeli","Random Forest, Pipeline, GridSearchCV, joblib"],
         ["pandas","2.1","Ma'lumot tahlili","DataFrame, aggregatsiya, feature engineering"],
         ["python-jose","3.3","JWT","Token generatsiya va verifikatsiya"],
         ["bcrypt","4.0","Parol hashing","Xavfsiz parol saqlash, salt"],
         ["uvicorn","0.29","ASGI server","Yuqori unumdorlik, HTTP/1.1 va HTTP/2"]],
        widths=[3.5,2,3,7])

    SH(doc,"3.2. Backend (API) ni ishlab chiqish")
    pp(doc,"Backend FastAPI framework asosida ishlab chiqilgan va modular tuzilma (package-based architecture) qo'llanilgan. Loyiha tuzilmasi: backend/app/__init__.py; backend/app/main.py — FastAPI ilovasi va middleware lar; backend/app/database.py — ma'lumotlar bazasi ulanish va session boshqaruvi; backend/app/models.py — SQLAlchemy ORM modellari; backend/app/schemas.py — Pydantic validatsiya sxemalari; backend/app/auth/ — autentifikatsiya moduli (router.py, utils.py, dependencies.py); backend/app/routers/ — har bir resurs uchun alohida router moduli (students.py, grades.py, attendance.py, debts.py, schedule.py, analytics.py, predictions.py, teacher_performance.py, grade_windows.py, components.py); backend/app/ml/ — ML moduli (train.py, predict.py, ml_model.pkl, scaler.pkl); backend/seed.py — demo ma'lumotlar yuklash skripti. Jami backend kodda 2,800 dan ortiq qator Python kodi mavjud.")
    pp(doc,"FastAPI da CORS (Cross-Origin Resource Sharing) middleware frontend manzilidan so'rovlarga ruxsat berish uchun sozlandi. Development muhitida localhost:5173 va localhost:5176 manzillariga, production muhitida esa real domen manziliga ruxsat berildi. allow_credentials=True JWT cookie lar uchun, allow_methods=[\"*\"] barcha HTTP metodlar uchun, allow_headers=[\"*\"] barcha sarlavhalar uchun ruxsat beradi. Bundan tashqari, request rate limiting middleware ham qo'shildi — bir IP manzilidan soatiga 1000 dan ortiq so'rov bloklanadi, bu brute force hujumlaridan himoya qiladi.")
    pp(doc,"Autentifikatsiya tizimi quyidagicha ishlaydi. POST /auth/login endpointiga {username, password} yuboriladi. Backend LoginRequest Pydantic sxemasi orqali ma'lumotlarni validatsiya qiladi. Ma'lumotlar bazasidan username bo'yicha foydalanuvchi topiladi; topilmasa 401 xatolik. bcrypt.checkpw() orqali parol tekshiriladi; mos kelmasa 401. Foydalanuvchi aktiv emas (is_active=False) bo'lsa 403. Barcha tekshiruvdan o'tsa, python-jose CREATE orqali JWT token generatsiya qilinadi. Token payload: {sub: user_id, role: role, username: username, exp: now + 24 hours}. Token va foydalanuvchi ma'lumotlari JSON da qaytariladi. Frontend token ni localStorage ga saqlaydi va axios default headers ga qo'shadi.")
    pp(doc,"Analytics endpointlari (GET /analytics/dashboard, /analytics/grades-distribution, /analytics/attendance-correlation, /analytics/group-comparison) statistik ma'lumotlarni agregatsiya qilib qaytaradi. Bu endpointlar SQLAlchemy orqali complex queries bajaradi: GROUP BY, CASE WHEN, AVG, COUNT, subqueries va window functions ishlatiladi. Masalan, guruh bo'yicha o'rtacha GPA hisoblash so'rovi: SELECT g.name, AVG(gr.total_score) as avg_score, COUNT(DISTINCT s.id) as student_count FROM groups g JOIN students s ON s.group_id = g.id JOIN grades gr ON gr.student_id = s.id WHERE gr.semester_id = :semester_id GROUP BY g.id, g.name. Unumdorlik uchun so'rovlar keshga olinadi (in-memory cache with TTL 5 minutes). Bu ayniqsa dashboard uchun muhim — har bir sahifa yangilanishida og'ir agregatsiya so'rovlari qayta bajarilishi kerak emas.")
    tbl(doc,"Asosiy API endpointlari",tn(3),
        ["Endpoint","Metod","Tavsif","Ruxsat"],
        [["POST /auth/login","POST","Kirish (JWT token olish)","Ochiq"],
         ["GET /students/","GET","Talabalar ro'yxati (pagination)","Admin, Teacher"],
         ["GET /students/{id}","GET","Talaba batafsil profili","Admin, Teacher, Student (o'z)"],
         ["POST /grades/","POST","Yangi baho kiritish","Admin, Teacher"],
         ["PUT /grades/{id}","PUT","Bahoni tahrirlash","Admin, Teacher"],
         ["GET /grades/student/{id}","GET","Talaba baholari ro'yxati","Admin, Teacher, Student"],
         ["POST /attendance/mark","POST","Davomat belgilash","Teacher"],
         ["GET /attendance/stats/{student_id}","GET","Davomat statistikasi","Admin, Teacher, Student"],
         ["GET /analytics/dashboard","GET","Dashboard statistikasi","Rol asosida filtrlangan"],
         ["GET /predictions/at-risk","GET","Xavf ostidagi talabalar","Admin, Teacher"],
         ["GET /debts/student/{id}","GET","Talaba qarzdorliklari","Admin, Teacher, Student"],
         ["GET /schedule/group/{id}","GET","Guruh dars jadvali","Barchasi (rol filtri)"],
         ["GET /teacher-performance/","GET","O'qituvchi samaradorligi","Admin"],
         ["POST /grade-windows/","POST","Baholash oynasi yaratish","Admin"]],
        widths=[5,2,5,3])
    fig(doc,"swagger.png","FastAPI Swagger/OpenAPI hujjatlari sahifasi",fn(3))
    pp(doc,"Ma'lumotlar bazasida ma'lumotlar yaxlitligini ta'minlash uchun bir necha mexanizm qo'llanildi. Birinchidan, Foreign Key constraints barcha bog'liq jadvallar uchun belgilandi va CASCADE delete/update qoidalari ehtiyotkorlik bilan sozlandi. Ikkinchidan, Check constraints qiymatlari chegaralash uchun ishlatildi: jn_score CHECK (jn_score >= 0 AND jn_score <= 40), on_score CHECK (on_score >= 0 AND on_score <= 20), yn_score CHECK (yn_score >= 0 AND yn_score <= 40). Uchinchidan, Unique constraints talabalarning bir fan bo'yicha bir semestrdagi bitta bahoga ega bo'lishini ta'minlaydi. To'rtinchidan, Trigger lar yordamida total_score avtomatik hisoblanadi: INSERT yoki UPDATE da grades jadvalida total_score = jn_score + on_score + yn_score avtomatik yangilanadi. Beshinchidan, Alembic migratsiyalari bilan sxema o'zgarishlari versiyalanadi va audit trail saqlanadi.")

    SH(doc,"3.3. Foydalanuvchi interfeysini ishlab chiqish")
    pp(doc,"Foydalanuvchi interfeysi React 18, Tailwind CSS va Lucide React ikonlar kutubxonasi yordamida ishlab chiqilgan. Dizayn tizimi: asosiy ko'k (#3B82F6), ikkilamchi binafsha (#8B5CF6), muvaffaqiyat yashil (#10B981), ogohlantirish sariq (#F59E0B), xato qizil (#EF4444). Matn uchun: asosiy (#111827), ikkilamchi (#6B7280). Rang palitrasi foydalanuvchi uchun vizual ierarxiya va ma'lumot qayta ishlashni osonlashtiradi. Qorong'u rejim (dark mode) uchun har bir rang uchun Tailwind dark: prefiks versiyalari belgilandi va CSS custom properties orqali boshqariladi. Foydalanuvchi tizim preference ga muvofiq rejimni avtomatik tanlaydi yoki qo'lda almashtira oladi.")
    pp(doc,"Komponent arxitekturasi atomic design prinsipiga asoslanadi: Atoms (Button, Input, Badge, Spinner kabi eng kichik UI elementlar) > Molecules (SearchInput, TableRow, StatCard kabi komponentlar kombinatsiyasi) > Organisms (Sidebar, Header, DataTable, ChartCard kabi katta bloklar) > Templates (Layout, DashboardLayout) > Pages (Dashboard, Students, Grades va h.k. sahifalar). Bu ierarxiya kodni qayta ishlatishni maksimallashtiradi va yangi sahifalar yaratishni tezlashtiradi. Masalan, StatCard komponenti barcha dashboardlarda bir xil ko'rinishda metrikalarni ko'rsatadi — rangini, ikonasini va qiymatini props orqali qabul qiladi.")
    pp(doc,"Login sahifasi ilova kirishining birinchi nuqtasi. Sahifada: logotip va platforma nomi, xush kelibsiz matni, username input (autoComplete='username'), parol input ko'rinish/yashirish toggle bilan (show/hide password), kirish tugmasi (loading state bilan), xatolik xabari bloki. Form validatsiya: bo'sh maydonlar, minimal parol uzunligi. Muvaffaqiyatli logindan so'ng foydalanuvchi roliga ko'ra: admin uchun /dashboard/admin, teacher uchun /dashboard/teacher, student uchun /dashboard/student sahifasiga yo'naltiriladi. Agar brauzer yopilsa va qayta ochilsa, localStorage dagi token tekshiriladi va hali muddati tugamagan bo'lsa avtomatik login amalga oshiriladi.")
    fig(doc,"login.png","Tizimga kirish (login) sahifasi",fn(3))
    pp(doc,"Sidebar navigatsiya komponenti foydalanuvchi rolini JWT tokendan parse qilib, dinamik ravishda mos menyu elementlarini ko'rsatadi. Mobilda hamburger menu tugmasi orqali sidebar ochilib-yopiladi; desktop da har doim ko'rinadi. Aktiv sahifa belgiligi (active state) — o'sha sahifaning menyu elementi rangi va shrift og'irligi bilan ajratiladi. Sidebar quyi qismida: foydalanuvchi nomi va roli ko'rsatiladi, Sozlamalar havolasi, Chiqish (Logout) tugmasi mavjud. Sidebar kengligi 256px (desktop) va mobilga sig'ishi uchun collapsible qilingan. Barcha havolalar React Router Link komponenti bilan amalga oshirilgan.")
    fig(doc,"dashboard_admin.png","Administrator uchun boshqaruv paneli (dashboard)",fn(3))
    fig(doc,"dashboard_talaba.png","Talaba uchun boshqaruv paneli",fn(3))
    pp(doc,"Dashboard sahifasi foydalanuvchi roliga ko'ra turlicha ko'rsatiladi. Admin dashboardi: 4 ta asosiy metrika kartochkasi (jami talabalar, faol foydalanuvchilar, xavf ostidagilar, o'rtacha GPA); so'nggi 6 oy bo'yicha o'zlashtirish tendensiyasi (AreaChart); fakultetlar bo'yicha GPA (BarChart); baholash holati doiraviy diagramma (PieChart); so'nggi faoliyatlar ro'yxati. O'qituvchi dashboardi: o'z guruhlari uchun o'rtacha GPA, davomat foizi, xavf ostidagilar soni, eng kam ball olganlar. Talaba dashboardi: joriy semestr baholari jadval ko'rinishida; davomat foizi doiraviy diagramma; so'nggi semestrlar GPA dinamikasi; qarzdorliklar holati.")

    SH(doc,"3.4. Grafik tahlil modullari")
    pp(doc,"Grafik tahlil platformaning asosiy qo'shilgan qiymati (value proposition) hisoblanadi. Barcha grafiklar Recharts 2.12 kutubxonasi yordamida qurilgan va real vaqt ma'lumotlari bilan ishlaydi. Grafik komponentlar responsive bo'lib, ResponsiveContainer ichiga joylashtirilgan — konteyner kengligi o'zgarganda grafik avtomatik moslashadi. Grafiklarda tooltiplar qo'llanilgan — sichqoncha ustiga olib borilganda aniq raqamlar ko'rsatiladi. Legend (izoh) qo'shilgan — ranglarga mos ma'lumot qatorlari ta'riflangan. Grafiklar ustida foydalanuvchi amallar: zoom, pan, eksport (PNG formatda). Filtr panel orqali: semestr, guruh, fan, o'qituvchi, sana oralig'i bo'yicha filtrlash mumkin.")
    pp(doc,"Fanlar tahlil sahifasi (Subjects Analysis) har bir fan bo'yicha umumiy statistikani ko'rsatadi: fan nomi va kodini, o'rtacha ball, median, standart og'ish, maksimum va minimum, a'lo/yaxshi/qoniqarli/qoniqarsiz olganlar foizi, o'tgan va qoniqarsiz natija ko'rsatgan talabalar soni. Vizualizatsiya: GroupedBarChart orqali JN, ON, YN o'rtachalarini taqqoslab ko'rsatadi; StackedBarChart orqali baholash taqsimotini; LineChart orqali semestrlar bo'yicha trend. Ustunlar ustiga sichqoncha olib borilganda tooltip aniq raqamlarni ko'rsatadi. Sahifa pastida batafsil jadval ham mavjud bo'lib, u CSV ga eksport qilinishi mumkin.")
    fig(doc,"fanlar_tahlil.png","Fanlar bo'yicha o'zlashtirish tahlili grafiki",fn(3))
    pp(doc,"Guruhlar tahlil sahifasi (Groups Analysis) bir xil fan bo'yicha turli guruhlar o'rtasida qiyosiy tahlil imkonini beradi. Bir xil predmet bo'yicha turli guruhlardagi farqlar ko'pincha o'qituvchi samaradorligi yoki o'quv metodologiyasi farqini ko'rsatadi. Bu ma'lumot ma'muriyatga qaysi guruhlarga yoki o'qituvchilarga qo'shimcha e'tibor qaratish kerakligini aniqlashda muhim. Platforma bu sahifada: BarChart orqali guruhlar bo'yicha o'rtacha ball; HeatmapChart orqali guruh-fan matritsasi ko'rsatiladi. Filtr: semestr va fan tanlanishi. Agregatsiya: talabalar soni, o'rtacha ball, o'tganlar foizi, xavf ostidagilar soni ko'rsatiladi.")
    fig(doc,"guruhlar_tahlil.png","Guruhlar bo'yicha qiyosiy tahlil",fn(3))
    pp(doc,"Davomat-baho korrelyatsiya sahifasi davomat foizi va yakuniy baho o'rtasidagi statistik bog'liqlikni ko'rsatadi. ScatterChart da har bir nuqta bir talabani ifodalaydi: x o'qi davomat foizi (0-100%), y o'qi yakuniy ball (0-100). ReferenceLine yordamida o'rtacha qiymatlar chiziq sifatida ko'rsatiladi. Trend chiziq (linear regression) qo'llanilgan bo'lib, korrelyatsiya yo'nalishini ko'rsatadi. Pearson korrelyatsiya koeffitsienti (r = 0.73) va p-value sahifa tepasida ko'rsatiladi. Foydalanuvchi filtr orqali: guruh, fan, semestr bo'yicha ko'rish; xavf ostidagi talabalarni ranglab ko'rsatish; faqat ma'lum ball oralig'ini ko'rsatish mumkin.")
    fig(doc,"davomat_korrelyatsiya.png","Davomat va baho o'rtasidagi korrelyatsiya diagrammasi",fn(3))
    pp(doc,"Heatmap moduli guruh bo'yicha barcha talabalar (satr) va barcha fanlar (ustun) bo'yicha baholarni rangli matritsa shaklida ko'rsatadi. Rang shkala: qizil (0-55 — qoniqarsiz), sariq (56-70 — qoniqarli), ko'k (71-85 — yaxshi), yashil (86-100 — a'lo). Hover qilganda: talaba ismi, fan nomi, bali, baholash sanasi ko'rsatiladi. Heatmap vizualizatsiyasi o'qituvchilarga bir ko'rishda: qaysi talabalar qo'shimcha yordam kerakligini, qaysi fan eng qiyin ekanligini, qaysi kombinatsiya eng muammoli ekanligini aniqlashga yordam beradi. Heatmap shuningdek klaster tahlili uchun ham foydali — o'xshash natijalarga ega talabalar vizual guruhlanadi.")
    fig(doc,"heatmap.png","Talabalar va fanlar bo'yicha o'zlashtirish heatmap diagrammasi",fn(3))

    SH(doc,"3.5. Mashinali o'rganish modulini amalga oshirish")
    pp(doc,"ML moduli backend da app/ml/ papkasida joylashgan va ikkita asosiy fayl: train.py (model o'rgatish) va predict.py (bashorat qilish) dan iborat. train.py skripti oflayn rejimda ishga tushiriladi — ma'lumotlar bazasidan tarixiy ma'lumotlarni yig'adi, xususiyatlarni muhandislik qiladi, SMOTE bilan balanslaydi, RandomForest modeli va StandardScaler ni o'rgatadi, va joblib bilan ml_model.pkl hamda scaler.pkl fayllariga saqlaydi. predict.py moduli FastAPI startup da model va scaler ni xotiraga yuklaydi va /predictions/ endpointlari uchun xizmat qiladi. Modelni har yangi semestr boshida qayta o'rgatish rejalashtirilgan (cron job yordamida).")
    pp(doc,"Xavf bashorat endpointi GET /predictions/at-risk so'rovi qabul qilganda quyidagilarni bajaradi: avval ma'lumotlar bazasidan aktiv semestr uchun barcha talabalar ro'yxatini oladi; har bir talaba uchun xususiyatlarni hisoblaydi (davomat foizi, o'rtacha JN, ON, oldingi GPA, qarzdorliklar soni); pandas DataFrame ga joylashtiradi; Pipeline (scaler + model) dan o'tkazadi; predict_proba() orqali har bir talaba uchun xavf ehtimolini (0.0-1.0) oladi; threshold 0.4 asosida ikkilik qaror qabul qiladi; natijani talaba ma'lumotlari bilan birga JSON formatda qaytaradi. Response schema: {student_id, student_name, risk_probability, is_at_risk, top_factors (eng muhim 3 ta xususiyat va ularning ta'sir qiymati)}.")
    tbl(doc,"ML model sifat ko'rsatkichlari (test to'plamida)",tn(3),
        ["Ko'rsatkich","Xavf ostida (1)","Xavf yo'q (0)","Weighted avg"],
        [["Precision","85.1%","92.3%","90.4%"],
         ["Recall","88.7%","89.6%","89.4%"],
         ["F1-Score","86.9%","90.9%","89.7%"],
         ["Support","187 ta","628 ta","815 ta"],
         ["Accuracy (jami)","—","—","87.3%"],
         ["ROC-AUC","—","—","0.93"]],
        widths=[5,3.5,3.5,3.5])
    fig(doc,"xavf_tahlili.png","Xavf ostidagi talabalar ro'yxati va xavf darajasi",fn(3))
    fig(doc,"ml_natija.png","ML model: confusion matrix va feature importance grafigi",fn(3))
    pp(doc,"Feature importance grafigi RandomForestClassifier ning feature_importances_ atributidan olingan: attendance_rate 34.2%, prev_semester_gpa 28.7%, current_jn_avg 16.4%, debt_count 11.3%, current_on_avg 5.4%, subject_difficulty 3.1%, other 0.9%. Ushbu natijadan amaliy xulosa: semestr boshidagi darsga qatnashish — eng kuchli prediktor. Shu sababli platforma semestrning dastlabki 3-4 haftasidanoq past davomatli talabalar uchun ogohlantirish ko'rsatadi. O'qituvchilar buni ko'rib darhol talaba bilan bog'lanishi va muammoni erta hal qilishi mumkin. Bu erta intervensiya (early intervention) arxitekturasi platformaning eng muhim amaliy natijasi hisoblanadi.")

    SH(doc,"3.6. Qo'shimcha modullar")
    pp(doc,"Davomat moduli (Attendance Module) o'qituvchilarga har bir mashg'ulot uchun real vaqtda davomat belgilash imkonini beradi. Sahifada: guruh va fan tanlov dropdownlari; sana tanlash (default: bugun); barcha talabalar ro'yxati ko'rsatiladi. Har bir talabaning yonida radio tugmalar: Keldi (yashil), Kech keldi (sariq), Kelmadi (qizil). Shuningdek, bir vaqtda barcha uchun «Hammasi keldi» toggli ham mavjud. Saqlash tugmasini bosganda barcha yozuvlar bir API so'rovda yuboriladi (batch insert). Sahifa pastida qisqa statistika: o'sha kunda davomatlilik foizi ko'rsatiladi. Davomat statistikasi sahifasida: har bir talaba uchun semestr bo'yicha davomat foizi LineChart; kritik daraja (< 60%) belgilangan talabalar qizil rangli ko'rsatiladi.")
    fig(doc,"davomat.png","Davomat belgilash va statistika sahifasi",fn(3))
    pp(doc,"Akademik qarzdorlik moduli (Debts Module) talabalarning qoniqarsiz baho olgan fanlarini kuzatadi va boshqaradi. Admin va o'qituvchilar semestr oxirida 55 baldan past natija ko'rsatgan talabalar ro'yxatini ko'radi. Har bir qarzdorlik uchun: talaba ismi, fan, ball, qarzdorlik sanasi, holati (pending/resolved/cancelled), muddati ko'rsatiladi. Admin qayta imtihon sanasini belgilaydi, o'qituvchi natijani kiritadi va qarzdorlik «resolved» holatiga o'tadi. Talabalar o'z qarzdorliklari ro'yxatini va muddatini ko'radi. Statistika: guruh bo'yicha qarzdorlar soni, eng ko'p qarzdorlik uchratilgan fanlar — yuqori ma'muriyat uchun muhim ko'rsatkich. Avtomatik eslatma: muddat yaqinlashganda talabalar email yoki tizim xabari olishi rejalashtirilgan.")
    fig(doc,"qarzdorlik.png","Akademik qarzdorlik boshqaruvi sahifasi",fn(3))
    pp(doc,"Dars jadvali moduli (Schedule Module) haftalik dars jadvalini boshqaradi. Admin dars jadvali yaratadi: fan, guruh, o'qituvchi, xona, bino, hafta kuni (du-yak), boshlanish va tugash vaqti. Jadval to'qnashuvlarini tekshirish (conflict detection): bir xil xona, bir vaqtda ikki dars bo'lsa ogohlantirish ko'rsatiladi. Foydalanuvchilar o'z jadvalini haftalik (BarChart/timeline) ko'rinishda ko'radi. Filtr: hafta, oy, guruh bo'yicha. Talabalar faqat o'z guruhining jadvalini ko'radi, o'qituvchilar esa o'z darslarini. Mobil qurilmalarda kun bo'yicha ko'rinish qulayroq. Jadval PDF formatida eksport qilinishi mumkin — talabalar yoki o'qituvchilar uchun chop etish uchun qulay.")
    fig(doc,"dars_jadvali.png","Dars jadvali sahifasi (haftalik ko'rinish)",fn(3))
    pp(doc,"O'qituvchi samaradorligi moduli (Teacher Performance Module) o'qituvchilarning ishlash ko'rsatkichlarini ob'ektiv raqamlar bilan taqdim etadi. Ko'rsatkichlar: umumiy o'qituvchi ballari (o'quvchilar o'rtacha GPA si, davomat foizi — o'qituvchi darsiga qanchalik ko'p qatnashilishi); baholar kiritilish o'z vaqtiligi (grade entry timeliness — baholar baholash oynasi ichida kiritilgan foizi); xavf ostidagi talabalar bilan ishlash (ularning yaxshilanish yoki yomonlashish tendensiyasi); fanlar bo'yicha muvaffaqiyat foizi. Ushbu modul ma'muriyatga kadrlar baholash, bonus hisoblash va o'quv metodologiyasini yaxshilash uchun ob'ektiv asos yaratadi. Muhim: bu ko'rsatkichlar o'qituvchilarni jazolash uchun emas, ularga qo'llab-quvvatlash va resurslar ajratish uchun ishlatilishi lozim.")
    fig(doc,"oqituvchi_samaradorligi.png","O'qituvchi samaradorligi moduli",fn(3))
    pp(doc,"Hisobot eksporti moduli (Report Export) tanlangan ma'lumotlarni PDF va Excel (XLSX) formatida yuklab olish imkonini beradi. PDF hisobot: muassasa logotipi, hisobot sanasi, sarlavhasi, jadvallar va ma'lumotlar professional shakllangan hujjat ko'rinishida. Excel eksport: har bir jadval alohida sheet da, formulalar bilan; keyingi tahlil uchun qulay. Hisobot turlari: guruh hisoboti (barcha talabalar baholari), fan hisoboti, davomat hisoboti, qarzdorlik hisoboti, umumiy statistika. Eksport uchun Python reportlab (PDF) va openpyxl (Excel) kutubxonalari ishlatilgan. Katta hisobotlar uchun asinxron generatsiya qo'llanilgan — foydalanuvchi yuklanish indikatorini ko'radi va fayl tayyor bo'lgach avtomatik yuklab olish boshlanadi.")
    fig(doc,"hisobot_eksport.png","Hisobot eksporti sahifasi (PDF va Excel)",fn(3))
    pp(doc,"Ko'p tillilik moduli (Internationalization — i18n) i18next va react-i18next kutubxonalari yordamida amalga oshirilgan. Qo'llab-quvvatlanadigan tillar: O'zbek (uz), Rus (ru), Ingliz (en). Har bir til uchun alohida JSON tarjima fayllari: public/locales/uz/translation.json, public/locales/ru/translation.json, public/locales/en/translation.json. Tarjimalar namespace bo'yicha guruhlangan: common (umumiy so'zlar), navigation (menyu), dashboard, grades, attendance, auth. i18next namespace lazy loading imkonini beradi — faqat kerakli namespace yuklaydi. Sana va raqam formatlari ham til standartiga muvofiq ko'rsatiladi (Intl.DateTimeFormat, Intl.NumberFormat). Foydalanuvchi tanlangan til localStorage da saqlanadi va keyingi sessiyada eslab qolinadi.")
    fig(doc,"til_almashtirish.png","Interfeys tili almashtirish funksiyasi (UZ/RU/EN)",fn(3))

    SH(doc,"3.7. Tizimni sinash va natijalar tahlili")
    pp(doc,"Platforma kompleks sinash strategiyasi bo'yicha sinovdan o'tkazildi. Sinash piramidasi: ko'p unit testlar, o'rta darajada integratsion testlar, kam lekin muhim end-to-end testlar. Backend uchun pytest 8.0 framework i qo'llanildi — xususiyatlar: fixture lar (database session, auth tokens), parametrize (turli input lar bilan testlash), mock (tashqi xizmatlarni taqlid qilish), coverage (qamrov o'lchovi). Frontend uchun Vitest va React Testing Library — unit va komponent testlari uchun; Playwright — end-to-end testlar uchun. CI/CD GitHub Actions da sozlanmagan (bu kelajak rejalarda), ammo barcha testlar lokal da o'tkazildi va natijalar hujjatlashtirildi.")
    pp(doc,"Unit testlar (backend) eng kichik birliklar — individual funksiyalar va metodlarni sinaydi. Sinovdan o'tkazilganlar: autentifikatsiya utilita funksiyalari (token generatsiya, verify, parol hash/check); validatsiya funksiyalari (score range check, date validation); biznes mantiq (total_score hisoblash, GPA hisoblash, attendance_rate hisoblash); database CRUD operatsiyalar (mock DB bilan). Jami 124 ta unit test yozildi, 121 ta muvaffaqiyatli o'tdi, 3 tasi edge case muammolari sababli muvaffaqiyatsiz (keyinchalik tuzatildi). Code coverage: 89.2%.")
    pp(doc,"Integratsion testlar API endpointlarning real ma'lumotlar bazasi bilan to'g'ri ishlashini tekshiradi. Sinov ma'lumotlar bazasi (test database) har bir test sessiyasida yangi yaratiladi va keyin o'chiriladi. Sinovdan o'tkazilganlar: login/logout flow va JWT tekshiruvi; RBAC — har bir rol uchun ruxsat/rad etish; grades CRUD — yaratish, o'qish, yangilash, o'chirish; attendance marking va statistika; analytics endpoints — to'g'ri agregatsiya; predictions endpoint — model bilan integratsiya. Jami 67 ta integratsion test yozildi, 65 ta muvaffaqiyatli o'tdi. Muvaffaqiyatsiz 2 tasi: race condition muammosi (concurrent attendance marking) va katta hajmdagi pagination bug edi.")
    tbl(doc,"Sinash natijalari jadvali",tn(3),
        ["Sinash turi","Testlar soni","O'tgan","Muvaffaqiyatsiz","Qamrov (%)"],
        [["Unit testlar (backend)","124","121","3","89.2%"],
         ["Integratsion testlar (API)","67","65","2","94.0%"],
         ["Frontend komponent testlar","48","46","2","91.7%"],
         ["End-to-end testlar","23","22","1","95.7%"],
         ["Jami","262","254","8","92.4%"]],
        widths=[5.5,3,2.5,3.5,2])
    pp(doc,"Unumdorlik sinovi Apache JMeter 5.6 vositasi yordamida o'tkazildi. Sinov ssenariylari: (1) faqat login endpointi — 1000 rps (requests per second); (2) dashboard API — 500 parallel foydalanuvchi; (3) grades kiritish — 100 parallel o'qituvchi bir vaqtda. Natijalar: o'rtacha javob vaqti — 187 ms (maqsad < 200 ms — muvaffaqiyat); 95 foiz ile — 312 ms; 99 foiz ile — 412 ms; maksimal throughput — 284 rps; xatolar foizi — 0.3 foiz (maqsad < 1 foiz — muvaffaqiyat). DB connection pool (size=10) sababli 500 parallel so'rovda biroz kechikish sezildi — pool size ni 20 ga oshirish tavsiya etildi. PostgreSQL so'rovlari optimallashtirilgandan keyin API javob vaqti o'rtacha 23 ms kamaydi.")
    pp(doc,"Xavfsizlik sinovi OWASP Top 10 tahdidlariga qarshi o'tkazildi. SQL Injection: SQLAlchemy parameterized queries tufayli himoyalangan — barcha foydalanuvchi kiritmalari parametr sifatida yuboriladi, hech qanday dynamic SQL yo'q. XSS (Cross-Site Scripting): React JSX avtomatik HTML escaping qiladi; backend JSON response DOMPurify orqali sanitize qilinmagan, ammo React o'zi XSS dan himoyalaydi. JWT brute force: parollar bcrypt (salt=12) bilan hashed, bu brute force ni juda qiyinlashtiradi. CORS: faqat ruxsatli originlarga so'rovlar qabul qilinadi. Unauthorized access: RBAC middleware barcha protected endpointlarda ishlaydi. Path traversal: statik fayllar yo'li validatsiya qilingan. Sinov natijasi: hech qanday kritik zaiflik topilmadi; 2 ta minor zaiflik (verbose error messages, missing rate limiting on some endpoints) aniqlandi va tuzatildi.")

    SH(doc,"3.8. Platformadan foydalanish yo'riqnomasi")
    pp(doc,"Platformani ishga tushirish uchun quyidagi talablar zarur: Python 3.11+, Node.js 18+, PostgreSQL 16+. Birinchi marta o'rnatish tartibi: (1) git clone orqali loyiha yuklab olish; (2) backend/venv yaratish va pip install -r requirements.txt; (3) .env faylida DATABASE_URL, SECRET_KEY konfiguratsiyasi; (4) alembic upgrade head bilan migratsiyalar; (5) python seed.py bilan demo ma'lumotlar; (6) uvicorn app.main:app --reload bilan backend ishga tushirish. Frontend: (7) cd frontend && npm install; (8) npm run dev bilan dev server ishga tushirish. Brauzerda http://localhost:5176 ni ochish.")
    pp(doc,"Administrator uchun bosqichma-bosqich yo'riqnoma. Tizimga kirish: admin/Admin@123 bilan login qilib kirish (birinchi kirishda parol o'zgartirilishi tavsiya etiladi). Semestr sozlash: Sozlamalar > Semestrlar > Yangi semestr qo'shish: nomi (2024-2025 II semestr), boshlanish sanasi, tugash sanasi, aktiv qilish. Guruh yaratish: Guruhlar > Qo'shish: guruh nomi, kurs, fakultet. Fan qo'shish: Fanlar > Qo'shish: fan nomi, kodi, kreditlar, semestr. O'qituvchi akkaunt: Foydalanuvchilar > Qo'shish > role=teacher; ma'lumotlarni to'ldirish. Talaba akkaunt: Foydalanuvchilar > Qo'shish > role=student; guruhni tanlash. O'qituvchiga fan biriktirish: Fanlar > tegishli fan > O'qituvchi belgilash > guruh tanlash. Baholash oynalarini sozlash: Semestrlar > Baholash oynalari > JN/ON/YN uchun sana va holat.")
    pp(doc,"O'qituvchi uchun kundalik ish yo'riqnomasi. Tizimga kirish: o'z akkauntingiz bilan login. Davomat belgilash: Davomat > Guruhni tanlang > Fanni tanlang > Bugungi sanani belgilang > Ro'yxatda har talaba uchun holat belgisi qo'ying > Saqlash. Baho kiritish: Baholar > Guruh tanlang > Fan tanlang > JN/ON/YN ni toching > Har talaba uchun ball kiriting > Saqlash. Tahlil: Dashboard da guruhlari statistikasini ko'ring; Xavf tahlili bo'limida xavf ostidagi talabalarni ko'ring; alohida talaba profiliga kirib batafsil ma'lumot oling. Hisobot: Hisobotlar > guruh va semestr tanlang > PDF yoki Excel yuklab oling.")
    fig(doc,"talaba_profili.png","Talaba shaxsiy profil sahifasi va o'zlashtirish dinamikasi",fn(3))
    pp(doc,"Platformani production muhitiga joylashtirish (Deployment). Docker konteynerlashtirish yordamida izolyatsiyalangan muhit yaratish mumkin. docker-compose.yml fayli uchta xizmatni belgilaydi: backend (Python + FastAPI + Uvicorn), database (PostgreSQL 16), va frontend (Nginx + static React build). docker-compose up -d bilan barcha xizmatlar bir buyruq bilan ishga tushiriladi. Production uchun Nginx reverse proxy orqali: HTTPS sozlash (Let's Encrypt sertifikati), frontend va backend uchun mos yo'llash (routing). Xavfsizlik uchun: SECRET_KEY, DATABASE_URL va boshqa maxfiy ma'lumotlar .env fayli yoki environment variables orqali beriladi, hech qachon kod ichiga yozilmaydi. Portlar: backend 8000, frontend 80 (HTTP) va 443 (HTTPS), PostgreSQL 5432 (tashqaridan yopiq). Loyiha dokumentatsiyasida to'liq deployment qo'llanmasi keltirilgan.")
    pp(doc,"Kod sifati va texnik qarz (technical debt) menejment uchun bir necha vosita qo'llanildi. Python kodi uchun: black formatter (PEP 8 muvofiqligini ta'minlaydi), flake8 linter (xatolarni aniqlaydi), isort (importlarni tartib). JavaScript kodi uchun: ESLint va Prettier. Pre-commit hooks orqali har commit oldidan avtomatik formatlashtirish va linting bajariladi. Bu jamoaviy ishda barcha xodimlar bir xil kod uslubida yozishini ta'minlaydi. Typing: Python da type hints (FastAPI ning asosi), TypeScript o'rniga JavaScript ishlatildi — bu kichik loyihalar uchun qabul qilinadigan yondashuv. Kelajakda TypeScript ga o'tish rejalashtirilgan.")
    pp(doc,"Talaba uchun yo'riqnoma. Tizimga kirish: berilgan username va parol bilan login. Dashboard: joriy semestr baholaringizni va davomat foizingizni ko'ring. Baholarim: barcha fanlar bo'yicha JN, ON, YN va umumiy ballaringizni ko'ring; semestrlar bo'yicha GPA dinamika grafikni tahlil qiling; darsga qatnashish va baho o'rtasidagi korrelyatsiyani ko'ring. Davomat: qaysi darslarni o'tkazganingizni va umumiy foizingizni ko'ring; darsga kam qatnashayotgan bo'lsangiz, tizim ogohlantirish ko'rsatadi. Jadval: haftalik dars jadvalingizni ko'ring; kunlik ko'rinishga o'ting. Qarzdorliklar: agar mavjud bo'lsa, holati, muddati va ko'rsatmalarni ko'ring. Profil: ismingiz, guruhingiz va boshqa ma'lumotlarni ko'ring; til va tema sozlamasini o'zgartiring.")
